### ISSUE TITLE
RC for NOAA NCEI PERSIANN

### ISSUE THREAD

**Issue by scott-stevens** [PCMDI/obs4MIPs-cmor-tables#103]
source_name = 'NOAA NCEI PERSIANN'
release_year = '2014'
source_description = 'Precipitation Estimation from Remotely Sensed Information using Artificial Neural Network'
source_version_number = '1.1'
institution_id = 'NOAA-NCEI'
region = 'global'
source_type = 'satellite_retrieval'

No Nobs or StdErr

**Comment by gleckler1** [comment]
@scott-stevens Can you verify this source_id is only for pr?

**Comment by scott-stevens** [comment]
@gleckler1 @JimBiardCICS Yes, pr is the only variable we're using for this one.

**Comment by gleckler1** [comment]
@gleckler1 @JimBiardCics  thnks... source_id's now updated to include source_variables... let me know if you see probs
