### ISSUE TITLE
RC for NOAA NCEI SeaWinds

### ISSUE THREAD

**Issue by scott-stevens** [PCMDI/obs4MIPs-cmor-tables#104]
source_name = 'NOAA NCEI SeaWinds'
release_year = '2008'
source_description = 'Blended Sea Surface Winds'
source_version_number = '1.2'
institution_id = 'NOAA-NCEI'
region = 'global_ocean'
source_type = 'satellite_blended'

If StdDev ends up being included, then we'd like Nobs and StdDev, otherwise no.

**Comment by gleckler1** [comment]
@scott-stevens Is this entry for zonal (ua) and meridional (va) winds or will it be used for a magnitude only?

**Comment by scott-stevens** [comment]
@gleckler1 @JimBiardCICS We were just discussing that earlier and what would be the best way to handle it.  Within the same source files, we have all three (u, v, and magnitude).  Should that be three separate source_ids, or just the one?

**Comment by JimBiardCics** [comment]
@durack1 @gleckler1 @scott-stevens It will be uas, vas, and sfcWind. We have all three. It seems to me that we would have one source_id for all three, as they live in the same input file and are closely related.

**Comment by gleckler1** [comment]
@scott-stevens @JimBiardCics  @taylor13  @durack1 Your current source_description is informative but not too prescriptive - it is relevant for all 3 fields.  Right now I'd say it is ok as is, but will continue soul searching.    Related:  we are discussing adding an attribute to each key in the obs4MIPs_source_id.json which identifies which variable_ids the source_id info is valid for, e.g., in this case, something like:   source_variables = ['ua','va','uvas'] 

ps: I've not verified 'uvas' is correct name for surface wind magnitude in CMIP6 tables .

**Comment by JimBiardCics** [comment]
It's uas, vas, and sfcWind. They are all single-level quantities.

**Comment by gleckler1** [comment]
@scott-stevens @JimBiardCics  source_id updated to include this
