### ISSUE TITLE
RC for CMSAF CLARA-A

### ISSUE THREAD

**Issue by Funkensieper** [PCMDI/obs4MIPs-cmor-tables#111]
1) source_name = 'CMSAF-CLARA-A'
2) release_year = '2017'
3) source_description = 'CM SAF cLoud, Albedo and surface RAdiation dataset from AVHRR data'
4) source_version_number = '2.0'
5) institution_id = 'DWD'
6) region = 'global'
7) source_type = 'satellite_retrieval'

nobs: cltCLARA, clwtCLARA, pctCLARA, clivi, clwvi
stddev: cltCLARA, clwtCLARA, pctCLARA
stderr: none

**Comment by Funkensieper** [comment]
8. clCLARA, cltCLARA, clwCLARA, clwtCLARA, pctCLARA, clivi, clwvi, rsds, rsdscs

**Comment by rqwa** [comment]
I am currently preparing the CLARA-A dataset for obs4mips at DWD.
Since the RC request for CMSAF CLARA-A, CLARA-A moved from version 2.0 to 2.1. Would it be possible to update the current CLARA entry, since there is no obs4mips preparation of CLARA-A 2.0 planned anymore.

**Comment by sfinkens** [comment]
Pinging @gleckler1 :)
