### ISSUE TITLE
obs4MIPs_Amon.json ttbr entry has bad values

### ISSUE THREAD

**Issue by JimBiardCics** [PCMDI/obs4MIPs-cmor-tables#115]
The obs4MIPs_Amon.json entry for ttbr has bad values. It is causing CMOR to fail. The entry should be:

> 
        "ttbr":{
            "cell_measures":"",
            "cell_methods":"time: mean",
            "comment":"",
            "dimensions":"longitude latitude time",
            "frequency":"mon",
            "long_name":"Top of Atmosphere Brightness Temperature",
            "ok_max_mean_abs":"",
            "ok_min_mean_abs":"",
            "out_name":"ttbr",
            "positive":"",
            "standard_name":"toa_brightness_temperature",
            "type":"real",
            "units":"K",
            "valid_max":"",
            "valid_min":""
        },

**Comment by durack1** [comment]
@JimBiardCics looks like [these are the differences](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/Tables/obs4MIPs_Amon.json#L1344-L1360), `positive` is clearly wrong, what about `valid_max`, `valid_min`? (As we discussed yesterday, these would need to be defined in `cmor.set_variable_attribute` and won't propagate directly from the table, but are useful registered content if they are hard limits)

```
        "ttbr":{
...
            "positive":"time: mean",
...
            "valid_max":"375.0",
            "valid_min":"140.0"
},
```

**Comment by JimBiardCics** [comment]
@durack1 They aren't hard limits, and the min limit value is a bit of a mystery to me anyway. I think we threw values in those entries because we thought they would go into the output file, and weren't thinking about this being a general purpose entry for anyone that wants to create a brightness temperature variable.

**Comment by durack1** [comment]
@JimBiardCics, ok so you're recommending that these 3 quirky fields are set to `""`?

**Comment by JimBiardCics** [comment]
@durack1 Yes.
