### ISSUE TITLE
Table file obs4MIPs_Aday.json contains areacella references

### ISSUE THREAD

**Issue by JimBiardCics** [PCMDI/obs4MIPs-cmor-tables#120]
In my latest pull from the repository (2017-10-04 13:00:00Z) the obs4MIPs_Aday.json file contained cell_measures entries with the value "areacella". This is the only table (other than the fx table) that has such entries.

**Comment by durack1** [comment]
@JimBiardCics thanks for this, we'll get onto sorting this problem along with a number of other standing issues
