### ISSUE TITLE
add "source_variables" to writejson.py and update all existing datasets

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/obs4MIPs-cmor-tables#121]
If you are *registering content* (RC) for obs4MIPs, please fill out the requested information below.   If you want to create an issue about something else, please delete the text below and title your issue as appropriate.  

To register (or edit) some or all of the obs4MIPs RC, please title this github issue as follows:  
"RC for " + your source_name (as you define below), and indicate if you are modifying your input from an earlier issue

Note: It is presumed that you have already registered your proposed obs4MIPs contribution with the WDAC's task team.  If you have not, please do so now (https://goo.gl/forms/0QaXZXS8UFu24rl03) before registering content 
________________________________________________________________________________________________________
The following are required registered content (with example content). Please replace the example text below with your information:
1) source_name = 'GPCP'
2) release_year = '2011'
3) source_description = 'Global Precipitation Climatology Project'
4) source_version_number = '2.3'
5) institution_id = 'UofMD'
6) region = 'Global'
7) source_type = 'satellite_blended'
8) A list of CMIP variable_ids that the above information refers to.  In most cases it will only be for one variable_id.  If it is for more than one, please make sure your source_description is sufficiently general to apply to all relevant variable_ids.

If you are planning to provide ancillary files for Nobs or Stderr, please let us know (Yes or No).  If Yes, please indicate for which variable_ids, and we will promptly update the obs4MIPs_monNobs.json and obs4MIPs_monStderr.json CMOR tables.
________________________________________________________________________________________________________

See note 14 and Appendix II of the obs4MIPs data specifications (https://goo.gl/jVZsQl) for more information regarding registered content

**Comment by gleckler1** [comment]
@durack1 done and pushed to master

**Comment by durack1** [comment]
@gleckler1 great, will get onto #120 

Are you working on any other RC registration? Happy to wait till you're done

**Comment by durack1** [comment]
@gleckler1 ok, ping me when you're done.. I'll get the PR notices via email anyway, so when I see a final merge I can update and get #120 done
