### ISSUE TITLE
consult WDAC task team on Nobs, NSD and Stderr

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/obs4MIPs-cmor-tables#123]
The WDAC task team needs to discuss how to address these ancillary fields in the future.  This issue will be revisited after the TTs next telecon

**Comment by durack1** [comment]
Just noting that we now include [Tables/obs4MIPs_monStderr.json](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/Tables/obs4MIPs_monStderr.json) and [Tables/obs4MIPs_monNobs.json](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/Tables/obs4MIPs_monNobs.json). Adding a `standard deviation` would be possible too. Not sure this can be closed, but these details are also covered in the dupes #50 #96
