### ISSUE TITLE
update DWD RC

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/obs4MIPs-cmor-tables#124]
This to address issues 116-119

**Comment by Funkensieper** [comment]
Is there anything left to be done before the Cloud_cci variables can be included in the CV?

**Comment by gleckler1** [comment]
@Funkensieper  I think you have done everything you need to do.   We are still considering options on how best to accommodate day and night monthly averages.   We should be able to resolve it early this week.   Thanks for your patience!

**Comment by Funkensieper** [comment]
Just noticed a typo in obs4MIPs_source_id.json: It should be "CMSAF-SARAH-2-0" instead of "CMSAF-SARAH-2.0".

**Comment by durack1** [comment]
Thanks @Funkensieper there are a couple of tweaks required, and I'll add this correction into the list for #133
