### ISSUE TITLE
Review source_id format for regions and variables

### ISSUE THREAD

**Issue by durack1** [PCMDI/obs4MIPs-cmor-tables#133]
With recent updates regions and variable are now lists - they should be consistently typed across all current entries

**Comment by taylor13** [comment]
Won't CMOR have to be modified to ingest these new table structures?

**Comment by durack1** [comment]
I don't believe so, as we are formatting the registered content found in [obs4MIPs_source_id.json](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/obs4MIPs_source_id.json) when we produce the [Tables/obs4MIPs_CV.json](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/Tables/obs4MIPs_CV.json) file. Once the changes are made I'll test this with `CMOR 3.2.8` as there are a number of outstanding issues that should also be solved (#128, #129)

**Comment by durack1** [comment]
From @Funkensieper 
> Just noticed a typo in obs4MIPs_source_id.json: It should be "CMSAF-SARAH-2-0" instead of "CMSAF-SARAH-2.0".

**Comment by durack1** [comment]
Once validations are complete #116, #117, #118, #119 and #124 should be closed

**Comment by durack1** [comment]
@Funkensieper 
> Ah, and CMSAF-SARAH's source label and name are incorrect. Should be 

    "source_label":"CMSAF-SARAH",
    "source_name":"CMSAF SARAH"

instead of

    "source_label":"CMSAF-HOAPS",
    "source_name":"CMSAF HOAPS"

**Comment by durack1** [comment]
@Funkensieper the standing issues should now be fixed - would you mind taking a look over [obs4MIPs_source_id.json](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/obs4MIPs_source_id.json) to review?

**Comment by durack1** [comment]
@Funkensieper in the latest demo, the ncdump looks like - see https://github.com/PCMDI/obs4MIPs-cmor-tables/issues/136#issuecomment-343272251:

And this is using the registered content found [here](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/obs4MIPs_source_id.json#L270-L285)

So this issue should be resolved

**Comment by Funkensieper** [comment]
@durack1 Excellent! Source definitions are correct now. The region attribute, too.

**Comment by durack1** [comment]
@Funkensieper great, thanks for the feedback. Please do keep the feedback coming, we're getting there
