### ISSUE TITLE
Synchronizing correct registered content obs4MIPs1.0 vs obs4MIPs2.1

### ISSUE THREAD

**Issue by durack1** [PCMDI/obs4MIPs-cmor-tables#139]
It seems that we have a mismatch with the `institution_id` values in the existing [`obs4MIPs1.0`](https://earthsystemcog.org/search/obs4mips/):
```
CNES, ECMWF, IPSL, IUP, NASA-GSFC, NASA-JPL, NASA-LaRC, NCEI, PCMDI, REMSS, RSS, UOE, UW
```
versus those registered in the [`obs4MIPs2.1`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/obs4MIPs_institution_id.json):
```
DWD, JPL, NOAA-NCEI, PCMDI, RSS
```
To make these sync (in obs4MIPs2.1) we'll need to update `JPL -> NASA-JPL`, and also correct `RSS -> REMSS` (assuming Carl agrees with this)

@gleckler1

**Comment by taylor13** [comment]
what about NOAA-NCEI vs. NCEI ??

**Comment by durack1** [comment]
@taylor13 `NOAA-NCEI` is more descriptive than `NCEI`, so we'll keep that as is..

**Comment by gleckler1** [comment]
@durack1 @taylor13  We better go with what Jim Baird recently provided as RC

**Comment by durack1** [comment]
@taylor13 @gleckler1 exactly, which is the current entry [`NOAA-NCEI`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/obs4MIPs_institution_id.json#L5)

**Comment by durack1** [comment]
`NASA-JPL` fix is now completed, we'll need to keep this open as the re-write/republication starts
