### ISSUE TITLE
Add variable bt (brightness temperature)

### ISSUE THREAD

**Issue by JimBiardCics** [PCMDI/obs4MIPs-cmor-tables#14]
I would like to request addition of the variable described below to the obs4MIPs Amon table. The comment, ox_max_mean_abs, and ok_min_mean_abs elements of the table entry have not been specified.
```
"toabr":{
    "cell_measures":"time: mean",
    "cell_methods":"area: areacella",
    "comment":"",
    "dimensions":"longitude latitude time",
    "long_name":"Top of Atmosphere Brightness Temperature",
    "ok_max_mean_abs":"",
    "ok_min_mean_abs":"",
    "out_name":"toabr",
    "positive":"",
    "standard_name":"toa_brightness_temperature",
    "type":"real",
    "units":"K"
    "valid_max":"375.0",
    "valid_min":"140.0"
}
```

**Comment by durack1** [comment]
@JimBiardCics great, so do you want to edit `table_entry` to be your `variable_id`? (No worries - I just did - to `toabr`)

So for reference, [here](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/Tables/obs4MIPs_Amon.json#L1008-L1023) is the `tas` example:
```
        "tas":{
            "cell_measures":"time: mean",
            "cell_methods":"area: areacella",
            "comment":"near-surface (usually, 2 meter) air temperature",
            "dimensions":"longitude latitude time height2m",
            "long_name":"Near-Surface Air Temperature",
            "ok_max_mean_abs":"293",
            "ok_min_mean_abs":"262.4",
            "out_name":"tas",
            "positive":"",
            "standard_name":"air_temperature",
            "type":"real",
            "units":"K",
            "valid_max":"335.1",
            "valid_min":"180.6"
},
```

@gleckler1 would `toabr` be suitable?

**Comment by gleckler1** [comment]
@JimBiardCics @durack1 @m-p-t  twenty years ago today....
http://www-pcmdi.llnl.gov/projects/amip/DATASTDS/VARNAMES/main.html

From that ancient logic-less construct a more consistent acronym may be: ttbr ... or at least that is what I might have come up with in 1996...

**Comment by JimBiardCics** [comment]
I'd much rather the name bt, as it is shorter and well understood in the observations community. The name tb would be fine too.

**Comment by durack1** [comment]
@JimBiardCics in addition to the 20 year old logic of @gleckler1, it might be better practice to convolve the CF standard_name into whatever we come up with so `"standard_name":"toa_brightness_temperature",` the `toa` bit is what made me try out the `toabr`

**Comment by JimBiardCics** [comment]
The thing that causes me the most concern about toabr is that it misses the all important 't' for temperature. Maybe 'toabt'?

**Comment by gleckler1** [comment]
@JimBiardCics @durack1 @taylor13   .... the old gleck logic the prefix is the measurable.... that being "t"
ttbr is for 
t - temperature
t - top
br - brightness...

origins of top....
rlut (olr)
r - radiation
l - longwave
u - upward
t - top

**Comment by durack1** [comment]
@gleckler1 @JimBiardCics it worked in 1998, that works for me now.. @JimBiardCics?

**Comment by JimBiardCics** [comment]
I'm good with that.

**Comment by durack1** [comment]
@JimBiardCics give the master a rip - `ttbr` is now in
