### ISSUE TITLE
RC for ESA CCI SSH

### ISSUE THREAD

**Issue by khurst1** [PCMDI/obs4MIPs-cmor-tables#151]
If you are *registering content* (RC) for obs4MIPs, please fill out the requested information below.   If you want to create an issue about something else, please delete the text below and title your issue as appropriate.  

To register (or edit) some or all of the obs4MIPs RC, please title this github issue as follows:  
"RC for " + your source_name (as you define below), and indicate if you are modifying your input from an earlier issue

Note: It is presumed that you have already registered your proposed obs4MIPs contribution with the WDAC's task team.  If you have not, please do so now (https://goo.gl/forms/0QaXZXS8UFu24rl03) before registering content 
________________________________________________________________________________________________________
The following are required registered content (with example content for each item in **bold**). Please replace the example text below with your information to the right of the equal sign (DO NOT MAKE ANY CHANGES TO THE LEFT HAND SIDE OF THE EQUAL SIGN):
1) source_id['source_id'][key][**'source_name'**] = 'ESA CCI SSH'
2) source_id['source_id'][key][**'release_year'**] = '2016'
3) source_id['source_id'][key][**'source_description'**] = 'European Space Agency CCI Sea Surface Height above Geoid'
4) source_id['source_id'][key][**'source_version_number'**] = '2.0'
5) source_id['source_id'][key][**'institution_id'**] = 'ESA, CLS, CNES'
6) source_id['source_id'][key][**'region'**] = 'Global'
7) source_id['source_id'][key][**'source_type'**] = 'satellite_retrieval'
8) A list of CMIP variable_ids that the above information refers to.  In most cases it will only be for one variable_id.  If it is for more than one, please make sure your source_description is sufficiently general to apply to all relevant variable_ids.
'zos'

________________________________________________________________________________________________________

See note 14 and Appendix II of the obs4MIPs data specifications (https://goo.gl/jVZsQl) for more information regarding registered content, and feel free to ask questions!

**Comment by gleckler1** [comment]
@durack1 @taylor13 
'institution_id' = 'ESA, CLS, CNES' has been proposed for this source_id because it results from a multi-institutional collaboration.    We could create a new entry for 'ESA-CLS-CNES-collaboration' or just ''ESA-CLS-CNES'.    Any thoughts?

@khurst1   What does "CLS" stand for?

**Comment by durack1** [comment]
@gleckler1 not that it's perfect, but for reference take a peek at [CMIP6_institution_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/) for examples

**Comment by khurst1** [comment]
@gleckler1 CLS stands for Collecte Localisation Satellites (France)

**Comment by durack1** [comment]
@gleckler1 one of the key pieces that I was trying to capture in the registration was address details, so inevitably when we want to visualize all the contributing institutions on a map (ala ESGF), this will be trivial from the registered content. For this reason the format that I am recommending follows:
```
"PCMDI":"Program for Climate Model Diagnosis and Intercomparison, Lawrence Livermore National Laboratory, Livermore, CA 94550, USA"
```
In the case of a multi-institute consortia, the `master` institution gets the last entry which follows the above, see [`EC-Earth-Consortium`](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_institution_id.json#L16)

And yes, the registration/issue guidance for institution registration is at [Institution_registration_template.md](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/.github/Institution_registration_template.md)
