### ISSUE TITLE
RC for NOAA NCEI SeaIce

### ISSUE THREAD

**Issue by JimBiardCics** [PCMDI/obs4MIPs-cmor-tables#155]
source_id['source_id'][key]['source_name'] = 'NOAA NCEI SSMI SeaIce'
source_id['source_id'][key]['release_year'] = '2013'
source_id['source_id'][key]['source_description'] = 'SSMI Passive Microwave Sea Ice Area Fraction'
source_id['source_id'][key]['source_version_number'] = '2.0'
source_id['source_id'][key]['institution_id'] = 'NOAA-NCEI'
source_id['source_id'][key]['region'] = 'global_ocean'
source_id['source_id'][key]['source_type'] = 'satellite_retrieval'
['siconc']

@durack1, @gleckler1 This request is part of preparing for updating the CMIP5-compatible SeaIce product to the new CMIP6-compatible form. There are a few issues to address along the way.
* There are daily and monthly versions of this product.
* The variable name in the current files is __sic__, not __siconc__. 
* All files contain a __sic__ variable and a __sicStddev__ variable.
* There are separate sets of files for Northern Hemisphere and Southern Hemisphere. The contents are on North and South Polar Stereographic coordinate grids, respectively. I'm not sure how this impacts this RC. Should there be two that define different regions - _arctic\_ocean_ and _southern\_ocean_ instead of single one that uses the _global\_ocean_ region? This last issue may be resolved by using the proposed gnNH and gnSH grid labels on the individual files.

**Comment by JimBiardCics** [comment]
@gleckler1 We will likely drop the standard deviation variable when converting this. We can sort out how to use the ancillary data option at some point. (Same with the OISST and OLR datasets.)

**Comment by gleckler1** [comment]
@JimBiardCics ok.  What about Nobs?

**Comment by JimBiardCics** [comment]
The same for Nobs I guess. It's ancillary as well, right? Or do you have a different suggestion?
