### ISSUE TITLE
Add variable ndvi (Normalized Difference Vegetation Index)

### ISSUE THREAD

**Issue by JimBiardCics** [PCMDI/obs4MIPs-cmor-tables#16]
I would like to request addition of the variable described below to the obs4MIPs Lmon table. The comment, ok_max_mean_abs, and ok_min_mean_abs elements of the table entry have not been specified.

```
"ndvi":{
    "cell_measures":"time: mean area: mean where land",
    "cell_methods":"area: areacella",
    "comment":"",
    "dimensions":"longitude latitude time",
    "long_name":"Normalized Difference Vegetation Index",
    "ok_max_mean_abs":"",
    "ok_min_mean_abs":"",
    "out_name":"ndvi",
    "positive":"",
    "standard_name":"normalized_difference_vegetation_index",
    "type":"real",
    "units":"1"
    "valid_max":"1.0",
    "valid_min":"-0.1"
}
```

**Comment by durack1** [comment]
@gleckler1 I think you need to chime in here too..

**Comment by gleckler1** [comment]
@JimBiardCics @durack1 @taylor13  Our first case!  We will develop a path to add this and other "not in CMIP6 but being added to obs4MIPs" variables which will be appended to Lmon and other tables.    Regarding the variable id,  we'll have to think if we want to stick to old construction logic (which might lead us to "vndi") or an alternate path like following standard name ("ndvi") which is more recognizable to those who care
