### ISSUE TITLE
Q: how to identify nominal_resolution for a dataset?

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/obs4MIPs-cmor-tables#160]
@durack1 @taylor13  I don't see how the nominal_resolution for a particular dataset is entered into our production line.  I'm not asking how one selects a value, but _who_ does it and how is it documented... Since it is not part of our RC (below), either we ask the data providers to follow instructions to determine a value or... we have to do it ourselves... YIKES!    Any thoughts?

If you are *registering content* (RC) for obs4MIPs, please fill out the requested information below.   If you want to create an issue about something else, please delete the text below and title your issue as appropriate.  

To register (or edit) some or all of the obs4MIPs RC, please title this github issue as follows:  
"RC for " + your source_name (as you define below), and indicate if you are modifying your input from an earlier issue

Note: It is presumed that you have already registered your proposed obs4MIPs contribution with the WDAC's task team.  If you have not, please do so now (https://goo.gl/forms/0QaXZXS8UFu24rl03) before registering content 
________________________________________________________________________________________________________
The following are required registered content (with example content for each item in **bold**). Please replace the example text below with your information to the right of the equal sign (DO NOT MAKE ANY CHANGES TO THE LEFT HAND SIDE OF THE EQUAL SIGN):
1) source_id['source_id'][key][**'source_name'**] = 'GPCP'
2) source_id['source_id'][key][**'release_year'**] = '2011'
3) source_id['source_id'][key][**'source_description'**] = 'Global Precipitation Climatology Project'
4) source_id['source_id'][key][**'source_version_number'**] = '2.3'
5) source_id['source_id'][key][**'institution_id'**] = 'UofMD'
6) source_id['source_id'][key][**'region'**] = 'global'
7) source_id['source_id'][key][**'source_type'**] = 'satellite_blended'
8) A list of CMIP variable_ids that the above information refers to.  In most cases it will only be for one variable_id.  If it is for more than one, please make sure your source_description is sufficiently general to apply to all relevant variable_ids.

________________________________________________________________________________________________________

See note 14 and Appendix II of the obs4MIPs data specifications (https://goo.gl/jVZsQl) for more information regarding registered content, and feel free to ask questions!

**Comment by durack1** [comment]
@taylor13 has requested that @doutriaux1 generate software to ascertain this, so once the software is available, we can upload this to the repo, and close the issue

**Comment by taylor13** [comment]
For obs4MIPs, I expect nearly all grids will be latxlon regular grids, so you can easily compute the nominal resolution (without the use of Charle's code.  Tell me delta-lon and delta-lat, and I'll tell you the nominal resolution.  (See formula in Appendix 2 of https://goo.gl/v1drZ .)

**Comment by durack1** [comment]
The nominal_resolution package is now available, with documentation accessible at https://pcmdi.github.io/nominal_resolution/html/ and direct conda downloads from https://anaconda.org/pcmdi/nominal_resolution
