### ISSUE TITLE
Update demo suites

### ISSUE THREAD

**Issue by durack1** [PCMDI/obs4MIPs-cmor-tables#161]
We need to update the demos so that @JimBiardCics can contribute another demo. Adding subdirs (so demo -> demo/PCMDI-RSS) will enable this to occur.

Updating [src/writeJson.py](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/src/writeJson.py) will be required

**Comment by gleckler1** [comment]
@durack1  Maybe demo/PCMDI-RSS --> demo/PCMDI_CDMS, demo/NCEI_netcdf4 ?
