### ISSUE TITLE
obs4MIPs_coordinate.json table incorrect for regional data

### ISSUE THREAD

**Issue by taylor13** [PCMDI/obs4MIPs-cmor-tables#163]
The current coordinate table  is meant for use with global data.  For regional data the valid_max and valid_min specifications for longitude and latitude may need to be changed.  See https://github.com/PCMDI/cmor/issues/418 for an example.

**Comment by taylor13** [comment]
I closed 418 because the discussion belongs here.

**Comment by sfinkens** [comment]
Any progress on this issue? Or would it be ok to change the longitude coordinate range in the table from 0/360 to -180/180?

**Comment by taylor13** [comment]
If you are writing data that does not include all longitudes, then it makes sense to "break" the longitude coordinate where there is no data.  So, for example, if your longitude domain extends from -160 to 60, I would not specify in the coordinate table 0 to 360, but rather, for example, -160 to 60 .  -180 to 180 would also work for this case, I think.  Could someone run a check that CMOR can handle both of those options?

**Comment by sfinkens** [comment]
@taylor13 Thanks for the info! I tried -180/180 and -65/65, CMOR can handle them both.

**Comment by taylor13** [comment]
thanks for checking. I think this issue can probably now be closed.  The outcome is that obs4MIPs will allow data to be reported with longitudes outside the domain of 0 to 360 (which is what we specify for CMIP6) when there is less than global coverage of a data set.  For such data sets, the domain can be adjusted so that the "missing" longitudes are outside the domain and the domain is contiguous.  So, for example, data available only between -65 to 65 may be stored from -65 to 65, rather than from 0 to 360 with a big chunk of data missing between 65 and 295.

**Comment by rqwa** [comment]
I am currently working on the SARAH dataset and obs4mips only works with a modified version of the obs4MIPs-cmor-tables, as mentioned above. After some testing, I found a possible solution: Changing the `valid_min` value to -180, while keeping `valid_max` at 360n allowed me to process datasets with global, as well as regional coverage, without further modifications to the tables.
Would it be possible to implement this change or do I miss some unpleasant side effects?
