### ISSUE TITLE
Update from upstreams (01.00.29)

### ISSUE THREAD

**Issue by durack1** [PCMDI/obs4MIPs-cmor-tables#164]
To ensure that these tables are not diverging too far from the CMIP6 branch, update with 01.00.29 recent release from [PCMDI/cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables)

**Comment by gleckler1** [comment]
@durack1 why are you making a pull request now??   Its mucked me up.

**Comment by durack1** [comment]
@gleckler1 I haven't.

The big red "CLOSED" means this issue is closed, along with the PR #165 which went along with it

**Comment by durack1** [comment]
@gleckler1 this issue was closed, no idea why it’s now open, so closing
