### ISSUE TITLE
Maximum File Size

### ISSUE THREAD

**Issue by sfinkens** [PCMDI/obs4MIPs-cmor-tables#167]
Is there a file size limit in ODS-2.1? I believe I read something like 2GB per file in an earlier version...

**Comment by taylor13** [comment]
For CMIP6 output we have set no hard limits.  We have provided the following guidance: "File sizes of several 10’s of megabytes can usually be routinely handled by users, but those exceeding 2 gigabytes may be problematic for some."

**Comment by sfinkens** [comment]
Ok, thanks @taylor13 !

**Comment by durack1** [comment]
@sfinkens we recommend therefore that for long time histories, the files be broken into manageable chunks, so files < 2GB
