### ISSUE TITLE
RC for GPCP SG

### ISSUE THREAD

**Issue by jhz0** [PCMDI/obs4MIPs-cmor-tables#168]
If you are *registering content* (RC) for obs4MIPs, please fill out the requested information below.   If you want to create an issue about something else, please delete the text below and title your issue as appropriate.  

To register (or edit) some or all of the obs4MIPs RC, please title this github issue as follows:  
"RC for " + your source_name (as you define below), and indicate if you are modifying your input from an earlier issue

Note: It is presumed that you have already registered your proposed obs4MIPs contribution with the WDAC's task team.  If you have not, please do so now (https://goo.gl/forms/0QaXZXS8UFu24rl03) before registering content 
________________________________________________________________________________________________________
The following are required registered content (with example content for each item in **bold**). Please replace the example text below with your information to the right of the equal sign (DO NOT MAKE ANY CHANGES TO THE LEFT HAND SIDE OF THE EQUAL SIGN):
1) source_id['source_id'][key][**'source_name'**] = 'GPCP SG'
2) source_id['source_id'][key][**'release_year'**] = '2016
3) source_id['source_id'][key][**'source_description'**] = 'Global Precipitation Climatology Project Satellite-Gauge'
4) source_id['source_id'][key][**'source_version_number'**] = '2.3'
5) source_id['source_id'][key][**'institution_id'**] = 'NASA-GSFC'
6) source_id['source_id'][key][**'region'**] = 'global'
7) source_id['source_id'][key][**'source_type'**] = 'satellite_retrieval_and_gauge_analysis'
8) A list of CMIP variable_ids that the above information refers to.  In most cases it will only be for one variable_id.  If it is for more than one, please make sure your source_description is sufficiently general to apply to all relevant variable_ids.
variable_id = 'pr'

________________________________________________________________________________________________________

See note 14 and Appendix II of the obs4MIPs data specifications (https://goo.gl/jVZsQl) for more information regarding registered content, and feel free to ask questions!

**Comment by jhz0** [comment]
Please change:
source_id['source_id'][key]['source_type'] = 'satellite_retrieval_and_gauge_analysis'
to:
source_id['source_id'][key]['source_type'] = 'satellite_blended'

**Comment by jhz0** [comment]
OK, saw in another RC submission that satellite_merged is preferred to satellite_blended, that's OK with us too.

**Comment by gleckler1** [comment]
@jhz0  Thanks for updating the "source_type" ... via "controlled vocabulary", there is a limited number of options that can be searched once the data is published on ESGF, the options currently include 
https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/obs4MIPs_source_type.json

**Comment by gleckler1** [comment]
@jhz0   The "source name" is a crucial piece of information.   The spreadsheet you sent me refers to the top level dataset as "GPCP" and that is consistent with the data as it is currently published on ESGF.  Did the curators of this data ask you to change the source name to "GPCP SG", or do you know are these separate datasets ("GPCP" and "GPCP SG") ?
