### ISSUE TITLE
PrePARE for obs4MIPs

### ISSUE THREAD

**Issue by jhz0** [PCMDI/obs4MIPs-cmor-tables#172]
If you are *registering content* (RC) for obs4MIPs, please fill out the requested information below.   If you want to create an issue about something else, please delete the text below and title your issue as appropriate.  

To register (or edit) some or all of the obs4MIPs RC, please title this github issue as follows:  
"RC for " + your source_name (as you define below), and indicate if you are modifying your input from an earlier issue

Note: It is presumed that you have already registered your proposed obs4MIPs contribution with the WDAC's task team.  If you have not, please do so now (https://goo.gl/forms/0QaXZXS8UFu24rl03) before registering content 
________________________________________________________________________________________________________
Do I need to install PrePARE configured for the obs4MIPs tables? Using the --table-path flag results in an error:
`[Errno 2] No such file or directory: 'Tables/CMIP6_mon.json'`

________________________________________________________________________________________________________

See note 14 and Appendix II of the obs4MIPs data specifications (https://goo.gl/jVZsQl) for more information regarding registered content, and feel free to ask questions!

**Comment by durack1** [comment]
@jhz0 PrePARE is not currently configured to work with the obs4MIPs or input4MIPs projects, this is planned for future work, but is not currently available

**Comment by jhz0** [comment]
thanks for the quick reply.
