### ISSUE TITLE
Support missing value of 0 for "Nobs"-type ancillary variables

### ISSUE THREAD

**Issue by m-p-t** [PCMDI/obs4MIPs-cmor-tables#18]
The following came up during a local test for using CMOR to process the two ancillary data fields "spco2Nobs" and "spco2Stderr" (by manually/locally adding variables for those two to my local "Omon" table): 

In accordance with "obs4MIPsDatasetRequirements_v1.2.pdf", I had set all "spco2Nobs" cells with missing data to 0, and had set the "missing_value" attribute for the "spco2Nobs" variable to 0 as well. 

After running the Nobs file through CMOR, the ncdump of the output contains:

```
int spco2Nobs(time, lat, lon) ;
    [...]
    spco2Nobs:history = "2016-09-29T22:01:40Z altered by CMOR: replaced missing value flag (0) with standard missing value (1e+20). 2016-09-29T22:01:40Z altered by CMOR: Converted type from \'f\' to \'i\'." ;
    spco2Nobs:missing_values = -2147483648 ;
    spco2Nobs:_FillValue = -2147483648 ;
```

On the upside, before converting zero to 1e20 (and converting that to -2147483648 in turn), CMOR recognized all missing cells correctly, so the information about what is missing is preserved, and just the meta-information affected. However, zero as a missing value should probably still be supported (or the "obs4MIPsDatasetRequirements_v1.2.pdf" be changed).

**Comment by durack1** [comment]
@m-p-t @gleckler1 interesting.. I do wonder whether this should be submitted as a bug report for [PCMDI/cmor](https://github.com/PCMDI/cmor)

@dnadeau4 what do you think - is this a `cmor` problem?

**Comment by m-p-t** [comment]
Found the corresponding section:
https://github.com/PCMDI/cmor/blob/5f316c766786124c3ba14c83cfd90566e8ff8ec2/Src/cmor_variables.c#L1773-L1787

**Comment by durack1** [comment]
@dnadeau4 this is the issue that I came to discuss with you yesterday.. Long story short there were some quirks with `CMOR` rewriting data that had `missing_value = 0` as an `int` type.. That made me query whether we'd successfully catch cases where data passed to `CMOR` had types of `real*4`, `real*8`, `int8` etc

**Comment by dnadeau4** [comment]
This missing value `1e20` will supersede the one that your pass.  CMIP5 and CMIP6 forces `1e20` as a missing value.  It seems that this is done on purpose and it was otherwise before.    

Thew WIP must have decided to forced `1e20` at some point.  If you changed the Amon table `missing_value` attribute in the Header section that will work.

[CMIP6_Amon.json](https://github.com/PCMDI/cmor/blob/5f316c766786124c3ba14c83cfd90566e8ff8ec2/TestTables/CMIP6_Amon.json#L9)

[cmor.c](https://github.com/PCMDI/cmor/blob/cmor-3.1.3/Src/cmor.c#L665-L666) and

https://github.com/PCMDI/cmor/blob/cmor-3.1.3/Src/cmor_variables.c#L1826-L1838

**Comment by gleckler1** [comment]
@dnadeau4 @durack1 @m-p-t @taylor13 Changing the missing value in the header of the CMOR tables will apply to all variables in that table.   In obs4MIPs there will be submissions that are basically a sampling count (e.g., Nobs, int), so we'll have to decide how we want to deal with this.  There are arguments in favor or N=0 being set to missing, and as MPT indicates above that is how it was handled in the original obs4MIPs.   Bottom line here is that it is good to know we can make a choice here without there being a need to modify CMOR - having a dedicated table may be sufficient.

**Comment by durack1** [comment]
@dnadeau4 this is the issue that I came to discuss with you yesterday.. Long story short there were some quirks with `CMOR` rewriting data that had `missing_value = 0` as an `int` type.. That made me query whether we'd successfully catch cases where data passed to `CMOR` had types of `real*4`, `real*8`, `int8` etc

It would be good to augment the test cases so that such "fringe" examples are correctly written

**Comment by durack1** [comment]
```
From: Hollmann Rainer
Date: Thursday, May 11, 2017 at 1:51 AM
To: "Gleckler, Peter J.", "Waliser, Duane E (8000)"
Cc: "Taylor, Karl E.", "Nadeau, Denis", "Durack, Paul J.", "Ferraro, Robert D (8310)"
Subject: AW: data records for obs4MIPs

Dear Peter,
 
thanks for your email. Indeed, we went ahead to upgrade our CMOR routines to CMOR3. Overall it worked ….but we found the following: Obs4MIPs requires physical variables to be of type float with fill value 1E20 and number of observations to be of type integer with fill value 0. However, you can only specify one global fill value in a CMIP table, which leads to problems because 1E20 cannot be represented as 4 byte integer. As a workaround we define two tables, one for integer variables and one for float variables, and have to load the corresponding table before each cmor.write() call. 
However, it looks like the same problem as described in: https://github.com/PCMDI/obs4MIPs-cmor-tables/issues/18“
 
With best regards,
 
Rainer 
```

**Comment by taylor13** [comment]
Hi Rainer,
I'm pretty sure you can just add the line to your CMOR table:

integer_missing_value:   999

where obs4MIPs might want to define a standard "missing value" for integers which is outside the normal range of acceptable values (i've used "999" as an example).

I'd place the added line under the current "missing_value" line.
Let us know if that doesn't work.

thanks,
Karl

**Comment by Funkensieper** [comment]
Unfortunately, ``integer_missing_value`` is not recognized by CMOR 3.2.3: 

    C Traceback:
    In function: cmor_set_dataset_att                                                                                                                                                                                                            
    ! called from: cmor_load_table_internal  
    !                                                                                                                                                    
                                                                         
    !!!!!!!!!!!!!!!!!!!!!!!!!
    !
    ! Warning: table: , This keyword: integer_missing_value value (table: , This keyword: integer_missing_value value () is not a valid table header entry.!
     Use the user input JSON file to add custom attributes.
    !
    !!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by taylor13** [comment]
cc: @dnadeau4 
@Funkensieper - thanks for trying my suggestion.  integer_missing_value was certainly recognized by CMOR1, so I don't know why it was removed.  I'm glad you found a work-around, but I think we should put this on our to-do list of CMOR3 enhancements.

**Comment by durack1** [comment]
```
From: "Ferraro, Robert D (8310)"
Date: Tuesday, May 30, 2017 at 11:00 AM
To: "Taylor, Karl E.", Hollmann Rainer, "Gleckler, Peter J.", "Waliser, Duane E (8000)"
Cc: "Nadeau, Denis", "Durack, Paul J."
Subject: RE: AW: data records for obs4MIPs

Regarding integer “missing value” 
 
The Nobs values are integer counts of observations that go into the Standard Error calculation.   Here, the natural “missing value” would be zero (no observations).   I cannot think of any other integer valued data that might pertain to obs4MIPs.  However, if you want to define a generic integer missing value, it needs to be number that cannot possibly represent a valid entry.   So I would choose the largest negative 4 byte integer as “missing value”.
 
In calculating Standard Error, which should be a float, the CMIP missing value does quite nicely (1e20).
 
Robert
```

**Comment by durack1** [comment]
```
From: "Taylor, Karl E."
Date: Thursday, June 1, 2017 at 9:55 AM
To: "Ferraro, Robert D (8310)", Hollmann Rainer, "Gleckler, Peter J.", "Waliser, Duane E (8000)"
Cc: "Nadeau, Denis", "Durack, Paul J."
Subject: Re: AW: data records for obs4MIPs

This is an interesting case, since the value "0" has real meaning in the sense that in fact there are "0 observational values that were available for use in calculating a standard error".  Given this interpretation, perhaps the value should *not* be considered "missing".  What is missing, of course, is an estimate of "standard error" since there are no observations, so when this is the case it is appropriate to use 1.e20 for the standard error variable.

So, I would suggest that we don't need a missing value for Nobs.  Nevertheless, CMOR requires "missing_value" to be defined, so I like Robert's suggestion to set it to what I think the largest negative 4-byte integer is: -2**31 = -2,147,483,648  

By the way some interesting facts:
(2**31) - 1 is the largest *positive* 4-byte integer
(2**31) - 1 held the record as largest prime number known until 1867
(2**31) - 1 is  a special "double Mersenne prime", and is the largest such prime known to date.

Karl
```

**Comment by Funkensieper** [comment]
Such a lovely number! I would also prefer a missing value < 0, because in case nobs=0 the user knows that we know that there has been no observation. If nobs=fill_value it might be missing for any reason.

**Comment by Funkensieper** [comment]
I just saw, that CMOR-3.2.5 now supports ``integer_missing_value``

**Comment by durack1** [comment]
@Funkensieper can you issue a PR for this?

**Comment by Funkensieper** [comment]
Sure: #63
