### ISSUE TITLE
Issues with new ERSST, FAPAR, LAI, NDVI, and SeaIce source_id entries

### ISSUE THREAD

**Issue by JimBiardCics** [PCMDI/obs4MIPs-cmor-tables#180]
Thanks for the prompt turnaround on the RC requests! Some bugs appear to have crept in along the way.

1. The new ERSST entry was given the key name "NOAA-NCEI-FAPAR", and no new FAPAR entry was made.
1. The dictionary keys for the FAPAR, LAI, NDVI, and SeaIce entries were not given versioned names. Perhaps there has been a process change, but the older versions of these entries all had version numbers at the ends of the names.

The latest version of the obs4MIPs_source_id.json file has:
<table>
<tr>
<th>Old Key</th><th>Old Dataset Version</th>
<th>New Key</th><th>New Dataset Version</th>
</tr>
<tr>
<td>NOAA-NCEI-ERSST-4-0</td><td>4.0</td>
<td>?missing?</td><td>5.0</td>
</tr>
<tr>
<td>NOAA-NCEI-FAPAR-4-0</td><td>4.0</td>
<td>NOAA-NCEI-FAPAR (with ERSST contents)</td><td>5.0</td>
</tr>
<tr>
<td>NOAA-NCEI-LAI-4-0</td><td>4.0</td>
<td>NOAA-NCEI-LAI</td><td>5.0</td>
</tr>
<tr>
<td>NOAA-NCEI-NDVI-4-0</td><td>4.0</td>
<td>NOAA-NCEI-NDVI</td><td>5.0</td>
</tr>
<tr>
<td>NOAA-NCEI-SSMI-SeaIce-2-0</td><td>2.0</td>
<td>NOAA-NCEI-SSMI-SeaIce</td><td>3.1</td>
</tr>
<table>

**Comment by gleckler1** [comment]
@JimBiardCics  We'll rectify shortly.

**Comment by gleckler1** [comment]
@JimBiardCics  Unacceptable!  Bugs fixed but still need to include day tables.  TBC PJG

**Comment by gleckler1** [comment]
@JimBiardCics  @durack1 made Aday and Oday tables available.  Are they working for you?

**Comment by gleckler1** [comment]
@JimBiardCics  Were you ever able to verify these fixes?

**Comment by JimBiardCics** [comment]
I've been snowed under with other work. I should be getting back to this in the next couple of weeks. I'll let you know soon.
