### ISSUE TITLE
RC for ESA CCI SST

### ISSUE THREAD

**Issue by bjoernbroetz** [PCMDI/obs4MIPs-cmor-tables#188]
1) source_id['source_id'][key][**'source_name'**] = 'ESA CCI SST'
2) source_id['source_id'][key][**'release_year'**] = '2019'
3) source_id['source_id'][key][**'source_description'**] = 'Sea Surface Temperature (SST) from the European Space Agency Climate Change Initiative (ESA CCI)'
4) source_id['source_id'][key][**'source_version_number'**] = 'v2.1'
5) source_id['source_id'][key][**'institution_id'**] = 'UReading'
6) source_id['source_id'][key][**'region'**] = 'global'
7) source_id['source_id'][key][**'source_type'**] = 'satellite_merged'
8) variable_id = tos

**Comment by bjoernbroetz** [comment]
> Note: It is presumed that you have already registered your proposed obs4MIPs contribution with the WDAC's task team.  If you have not, please do so now (https://goo.gl/forms/0QaXZXS8UFu24rl03) before registering content

The data set was registered via the google form, recently.

**Comment by gleckler1** [comment]
@bjoernbroetz Has been included
