### ISSUE TITLE
RC for ESACCI-CLOUD-* (modification)

### ISSUE THREAD

**Issue by bjoernbroetz** [PCMDI/obs4MIPs-cmor-tables#197]
As discussed between DWD and the obs4MIPs Task Team (@gleckler1) the entries for the following datasets shall be changed from version 2 to version 3 (2017 to 2020):

- ESACCI-CLOUD-AVHRR-AM-2-0 to ESACCI-CLOUD-AVHRR-AM-3-0
- ESACCI-CLOUD-AVHRR-PM-2-0 to ESACCI-CLOUD-AVHRR-PM-3-0
- ESACCI-CLOUD-ATSR2-AATSR-2-0 to ESACCI-CLOUD-ATSR2-AATSR-3-0

Variables in all of the three datasets remain the same:
clCCI, clivi, cltCCI, clwCCI, clwtCCI, clwvi, pctCCI

The original entries have been introduced by #116, #117, and #118  

**ESACCI-CLOUD-ATSR2-AATSR**
1) source_id['source_id'][key][**'source_name'**] = 'ESACCI-CLOUD-ATSR2-AATSR'
2) source_id['source_id'][key][**'release_year'**] = '2020'
3) source_id['source_id'][key][**'source_description'**] = 'Cloud properties derived from ATSR2 and AATSR (aboard ERS2 and ENVISAT) measurements. This dataset belongs to the ESA Cloud_cci suite of long-term coherent cloud property datasets.'
4) source_id['source_id'][key][**'source_version_number'**] = '3.0'
5) source_id['source_id'][key][**'institution_id'**] = 'DWD'
6) source_id['source_id'][key][**'region'**] = 'global'
7) source_id['source_id'][key][**'source_type'**] = 'satellite_retrieval'
8) clCCI, cltCCI, clwCCI, clwtCCI, pctCCI, clivi, clwvi
 
**ESACCI-CLOUD-AVHRR-PM**
1) source_id['source_id'][key][**'source_name'**] = 'ESACCI-CLOUD-AVHRR-PM'
2) source_id['source_id'][key][**'release_year'**] = '2020'
3) source_id['source_id'][key][**'source_description'**] = 'Cloud properties derived from AVHRR (aboard NOAA and MetOp PM) measurements. This dataset belongs to the ESA Cloud_cci suite of long-term coherent cloud property datasets.'
4) source_id['source_id'][key][**'source_version_number'**] = '3.0'
5) source_id['source_id'][key][**'institution_id'**] = 'DWD'
6) source_id['source_id'][key][**'region'**] = 'global'
7) source_id['source_id'][key][**'source_type'**] = 'satellite_retrieval'
8) clCCI, cltCCI, clwCCI, clwtCCI, pctCCI, clivi, clwvi
(Nobs: cltCCI, clwtCCI, pctCCI, clivi, clwvi; Stddev: cltCCI, pctCCI)

**ESACCI-CLOUD-AVHRR-AM**
1) source_id['source_id'][key][**'source_name'**] = 'ESACCI-CLOUD-AVHRR-AM'
2) source_id['source_id'][key][**'release_year'**] = '2020'
3) source_id['source_id'][key][**'source_description'**] = 'Cloud properties derived from AVHRR (aboard NOAA and MetOp AM) measurements. This dataset belongs to the ESA Cloud_cci suite of long-term coherent cloud property datasets.'
4) source_id['source_id'][key][**'source_version_number'**] = '3.0'
5) source_id['source_id'][key][**'institution_id'**] = 'DWD'
6) source_id['source_id'][key][**'region'**] = 'global'
7) source_id['source_id'][key][**'source_type'**] = 'satellite_retrieval'
8) clCCI, cltCCI, clwCCI, clwtCCI, pctCCI, clivi, clwvi
(Nobs: cltCCI, clwtCCI, pctCCI, clivi, clwvi; Stddev: cltCCI, pctCCI)

**Comment by gleckler1** [comment]
@bjoernbroetz these ver 3 datasets have been added - please verify they are ok.  All the best PjG

**Comment by bjoernbroetz** [comment]
> @bjoernbroetz these ver 3 datasets have been added - please verify they are ok. All the best PjG

I think the original idea was to replace the v2 entries with the updated v3 entries instead of adding v3. I had a brief look to it and it doesn't seem to be so easy to do that. It seems to me that `src/writeJson.py` can only append to existing tables and not remove entries from it.

Apart from that it looks good to me. The actual data will be prepared by the colleagues from the DWD.

**Comment by bjoernbroetz** [comment]
There is a little bug with the changes in 70738ff80af2ff65e621813b126df31ee8f7b993 . A collegue noticed that the source id `ESACCI-CLOUD-ATSR2-AATSR` used in https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/obs4MIPs_source_id.json misses the "-3-0" at the end.

The documentation says that the source_id should be the source_label+ source_version_no, whereas in the table it’s equal to the source label only.   

This affects all three datasets that were changed:

    - ESACCI-CLOUD-AVHRR-AM to ESACCI-CLOUD-AVHRR-AM-3-0
    - ESACCI-CLOUD-AVHRR-PM to ESACCI-CLOUD-AVHRR-PM-3-0
    - ESACCI-CLOUD-ATSR2-AATSR to ESACCI-CLOUD-ATSR2-AATSR-3-0
