### ISSUE TITLE
Relax default license from CC BY-SA 4.0 to CC BY 4.0

### ISSUE THREAD

**Issue by durack1** [PCMDI/obs4MIPs-cmor-tables#214]
Roll back default license from CC BY-SA 4.0 to CC BY 4.0, see https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/obs4MIPs_license.json

Ref https://github.com/WCRP-CMIP/CMIP6_CVs/issues/1050 for context

@gleckler1 ping

**Comment by gleckler1** [comment]
@durack1 we need a generic license as a starting point, .e.g.,

"license":"Data in this file is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License (https://creativecommons.org/licenses/). Use of the data must be acknowledged if guidelines are provide here. 

and then work towards enabling product specific information as in: 

"license":"Data in this file produced by <Your Centre Name> is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License (https://creativecommons.org/licenses/). Use of the data must be acknowledged following guidelines found at <a URL maintained by you>. Further information about this data, including some limitations, can be found via <some URL maintained by you>."

And feedback on "starting point" above?

**Comment by durack1** [comment]
@gleckler1 the latest CMIP6 version can be found at https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_license.json - we recommend the "CC BY 4.0", but the other licenses are there for backward compatibility, and NASA-GISS decided that it wanted to go the CC0 license, which has no attribution (recognition/acknowledgment) clause
