### ISSUE TITLE
rss-prototyping

### ISSUE THREAD

**Issue by manaster** [PCMDI/obs4MIPs-cmor-tables#218]
Testing RSS prototyping branch for SMAP monthly mean salinity

**Comment by gleckler1** [comment]
@manaster Hey AM, just letting you know I've updated master with branch 217.  PG

**Comment by manaster** [comment]
Great!  Thanks for letting me know, Peter @gleckler1.

**Comment by gleckler1** [comment]
@manaster  PG has been experimenting with tpw_v07r01_198801_202112.nc4.nc downloaded from remss.  Xarrary/xcdat picks up the units of lon and lat (float), but for time (int) I've not been able to extract the units.  Have you run across something like this?

**Comment by manaster** [comment]
@gleckler1 yes, I have run into that very issue.  What 'xarray' and 'xcdat' like to do is convert 'time' variables in files they open from 'seconds since...' or 'days since...' to a datetime (I assume to make it more human readable).  However, when doing so, xarray or xcdat remove the 'units' from the time variable!  To prevent this, and to make things easier for cmor, I simply set the following keyword when calling xarray.open_dataset: "decode_times=False".  This should prevent 'xarray' or 'xcdat' from converting 'time' variables to datetimes and preserve the 'time' variable 'units' attribute in the process.  Let me know if that works for you.
