### ISSUE TITLE
obs4MIPs_grids.json has wrong structure.

### ISSUE THREAD

**Issue by JimBiardCics** [PCMDI/obs4MIPs-cmor-tables#22]
There is an extra single element dictionary layer with the key 'grids' in the obs4MIPs_grids.json file. This causes the cmor_load_table function to fail.

**Comment by dnadeau4** [comment]
@durack1 can you look what is wrong with this file?
https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/obs4MIPs_grids.json

**Comment by durack1** [comment]
@dnadeau4 we may have to talk about this, it seems that @gleckler1 was able to use these tables without an issue.. So not sure what is awry here. @JimBiardCics with the upstream changes in https://github.com/WCRP-CMIP/CMIP6_CVs, the obs4MIPs tables have been dragged along for the ride and so to have other CMOR tables...

**Comment by durack1** [comment]
@JimBiardCics are you using `CMOR 3.2.1` with the latest version of these (obs4MIPs) tables, we updated these a month ago?

**Comment by gleckler1** [comment]
@JimBiardCics @durack1 @dnadeau4   JB, hello!   We are working right now on 2 documents, one a reference doc updating the obs4MIPs data specifications, and the other a user guide for beginners.   Maybe Scott would be a good person to test out the user guide sometime in the next few weeks?

**Comment by JimBiardCics** [comment]
@durack1 I am using CMOR 3.2.1 with the latest version (Jan 31, 2017) of the obs4MIPs tables project. I have a small python script that attempts to build a CMOR grid object. When I use the CMIP6_grids.json file it works. When I use the obs4MIPs_grids.json file it doesn't.

[testCmorGrid.py.txt](https://github.com/PCMDI/obs4MIPs-cmor-tables/files/814870/testCmorGrid.py.txt)

When you run the script the arguments are the path to the measurements table you want to use (e.g. Tables/obs4MIPs_SImon.json), the path to a CMOR configuration JSON file (like the one below), and the name of the grids JSON file to use (without any path component).

[cmor_seaice.json.txt](https://github.com/PCMDI/obs4MIPs-cmor-tables/files/814880/cmor_seaice.json.txt)

I'm using the unmodified measurement table files copied from obs4MIPs-cmor-tables/Tables, an obs4MIPs_CV.json file prepared from the files in obs4MIPs-cmor-tables, and some files from cmip6-cmor-tables/Tables. Here's a list of the files in my final Tables folder:

CMIP6_coordinate.json
CMIP6_formula_terms.json
CMIP6_grids.json
obs4MIPs_Amon.json
obs4MIPs_CV.json
obs4MIPs_Lmon.json
obs4MIPs_Omon.json
obs4MIPs_SImon.json
obs4MIPs_fx.json
obs4MIPs_grids.json

And here are the actual files.


[Tables.zip](https://github.com/PCMDI/obs4MIPs-cmor-tables/files/814892/Tables.zip)

**Comment by JimBiardCics** [comment]
@gleckler1 Scott would likely be a great candidate!

**Comment by durack1** [comment]
@JimBiardCics is the data you're trying to write on a regular (lon/lat) grid?

**Comment by JimBiardCics** [comment]
It's on a polar stereographic grid.

**Comment by durack1** [comment]
thanks @JimBiardCics, there have been a heap of upstream changes in CMIP6 that need to be propagated back into this repo, so I'll fix this format issue you've highlighted at the same time.

**Comment by dnadeau4** [comment]
I wrote a test for polar grid using Greenland and Antartica data. 
https://github.com/PCMDI/cmor/issues/82
