### ISSUE TITLE
Can a total column ozone (toz) variable be added to the obs4mips tables?

### ISSUE THREAD

**Issue by alisonwaterfall** [PCMDI/obs4MIPs-cmor-tables#226]
Would it be possible to add the variable ‘toz’ (total column ozone) to the obs4mips tables? 
There is an existing CMIP variable (https://clipc-services.ceda.ac.uk/dreq/u/79fec430c1dca1ac4b48b0fc36c48449.html), but it doesn't seem to be present in the obs4mips tables.

We would like to submit some CCI/C3S monthly total column ozone data that would need to use this variable.

**Comment by taylor13** [comment]
The 'toz' variable for CMIP has the standard name equivalent_thickness_at_stp_of_atmosphere_ozone_content .  It is described as being "Total ozone column calculated at 0 degrees C and 1 bar, such that 1m = 1e5 DU."  Are the observations consistent with this?  If so, adding the variable should not be difficult.

**Comment by gleckler1** [comment]
@alisonwaterfall @taylor13 toz has just been [added](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/Tables/obs4MIPs_Amon.json#L1273), please confirm it checks out.  

Is the obs vertical integration calculated under same T and P as advised for model output?

**Comment by alisonwaterfall** [comment]
Thanks both.   
Yes, I believe the observations are consistent.   The original CCI dataset actually provides the data as "atmosphere_mole_content_of_ozone" in mol m-2, but they also provide a conversion factor to covert to DU, so it should be simple to produce an Obs4MIPs version that directly matches the CMIP definition.

**Comment by taylor13** [comment]
To be sure, in the CMIP archive the official units are specified as  "m" (rather than, say "1e5 DU"), so meters would best facilitate the use of the CCI data in analyzing models.  (Also, the CF conventions require the units to be "udunits interpretable", and I'm not sure "DU" is recognized by udunits.)

**Comment by gleckler1** [comment]
@alisonwaterfall @taylor13  Because we are mapping onto the CMIP tables, units='m' are expected and CMOR will through an error if they are not.
