### ISSUE TITLE
CMOR3 doesn't read obs4MIPs_coordinate.json, expects CMIP6_coordinate.json

### ISSUE THREAD

**Issue by JimBiardCics** [PCMDI/obs4MIPs-cmor-tables#23]
I must rename the obs4MIPs_coordinate.json file to CMIP6_coordinate.json in order for CMOR 3.2.0 to use it. This may be more of a CMOR issue, but one solution is to change the name.

**Comment by dnadeau4** [comment]
@JimBiardCics I fixed this in CMOR 3.2.2.  I passed a filename as an argument that you will be able to change.  Your are an **advanced user**!!

**Comment by JimBiardCics** [comment]
@dnadeau4 When will 3.2.2 be available with conda?

**Comment by durack1** [comment]
@JimBiardCics [`CMOR 3.2.2` was released today](https://github.com/PCMDI/cmor/releases/tag/CMOR-3.2.2) so we'll update the demos next week to reflect these changes.

@gleckler1 this will also require your demo1 update too

**Comment by durack1** [comment]
@JimBiardCics are you happy with the solution for this? If yes, then this is good to close

**Comment by JimBiardCics** [comment]
@durack1, @dnadeau4 I just tried a test after doing a conda update to 3.2.2 on cmor and doing a git pull and rebuild of obs4MIP-cmor-tables. No improvement. I don't see the new argument referred to above, and the demos don't seem to be updated. What do I need to do to use only the obs4MIPs files? In addition, the code also complains about needing CMIP6_formula_terms.json. There is no obs4MIPs version of that file.

**Comment by durack1** [comment]
@JimBiardCics we've found a couple of issues with the upstream [`cmip6-cmor-tables`](https://github.com/PCMDI/cmip6-cmor-tables/issues/53) which require a resolution before we can propagate the updates back down to the `obs4MIPs` and `input4MIPs` projects, I was working on resolving these issue for some `input4MIPs` data I was writing on Friday.. I'm hoping @dnadeau4 has some time to address this today, we'll keep you posted..

@gleckler1 has been working on updating the demos too, which you're right need to be incremented to deal with the additional issues you have encountered..

**Comment by durack1** [comment]
@JimBiardCics the updated `CMOR 3.2.2+` allows a user to specify the names of these input files, see [drive_input4MIPs_obs.json#L2-L4](https://github.com/PCMDI/amipbcs/blob/master/CMOR/drive_input4MIPs_obs.json#L2-L4) for a demo, this includes:
```
{
    "_control_vocabulary_file": "input4MIPs_CV.json",
    "_AXIS_ENTRY_FILE": "CMOR/input4MIPs-cmor-tables/input4MIPs_coordinate.json",
    "_FORMULA_VAR_FILE": "CMOR/input4MIPs-cmor-tables/input4MIPs_formula_terms.json",
    "activity_id": "input4MIPs",
...
```
Once the issues are resolved with [`cmip6-cmor-tables`](https://github.com/PCMDI/cmip6-cmor-tables) we can pull these across into this repo in preparation for `CMOR 3.2.3` which @dnadeau4 plans to release later in the week

**Comment by JimBiardCics** [comment]
@durack1 @dnadeau4 Do these new entries require full paths, or will the software look in the Tables folder for the files if they have no path part to their names?

**Comment by dnadeau4** [comment]
It will look in the inpath you path in the `cmor_setup()` function

**Comment by dnadeau4** [comment]
Actually,  inpath is concatenated to your "files".  Normally, all files are in the same directory.  In your example if `inpath="Tables"` your file will be found from the current directory where python is run.
```
CV: Tables/input4MIPs_CV.json
AXIS: Tables/CMOR/input4MIPs-cmor-tables/input4MIPs_coordinate.json
FORMULA: Tables/CMOR/input4MIPs-cmor-tables/input4MIPs_formula_terms.json
```

**Comment by JimBiardCics** [comment]
I tested this, and found that there is still no obs4MIPs_formula_terms.json file, so I must still copy over / use the CMIP6_formula_terms.json file. But I did see that it uses the obs4MIPs_coordinate.json file when I specify it in my config file.

**Comment by durack1** [comment]
@JimBiardCics a fair number of updates have just been implemented, including pulling the `formula_terms` into this repo. Take a look at the [`demo`](https://github.com/PCMDI/obs4MIPs-cmor-tables/tree/master/demo), and in particular the [`demo/drive_obs4MIPs.json`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/demo/drive_obs4MIPs.json) file which now [uses the `obs4MIPs_coordinate.json` and `obs4MIPs_formula_terms.json` explicitly](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/demo/drive_obs4MIPs.json#L3-L4)

I'll close this issue, please reopen if you find that you still hit errors

**Comment by JimBiardCics** [comment]
That took care of it! Thanks!

**Comment by durack1** [comment]
@JimBiardCics that's great news.. Please keep reporting any problems you encounter. There are many updates that are still flowing from the upstream (CMIP6 sources), but things are starting to coalesce
