### ISSUE TITLE
RC for RSS-PRW-v07r02

### ISSUE THREAD

**Issue by manaster** [PCMDI/obs4MIPs-cmor-tables#249]
I am creating an issue to include the Remote Sensing Systems (RSS) monthly, 1 degree precipitable water data (PRW).  There is currently a source ID for **RSS-PRW-v07r01**.  The information below is for the new **RSS-PRW-v07r02** source ID.

________________________________________________________________________________________________________
1) source_id['source_id'][key][**'source_name'**] = 'RSS-PRW'
2) source_id['source_id'][key][**'release_year'**] = '2022'
3) source_id['source_id'][key][**'source_description'**] = 'RSS-PRW 7.0 (2019): Water Vapor Path'
4) source_id['source_id'][key][**'source_version_number'**] = '7.2'
5) source_id['source_id'][key][**'institution_id'**] = 'RSS'
6) source_id['source_id'][key][**'region'**] = 'global'
7) source_id['source_id'][key][**'source_type'**] = 'satellite_merged'
8) prw

Let me know if any other information is required.

Andrew

**Comment by gleckler1** [comment]
@manaster source_id RSS-PRW-v07r02 has been added.
