### ISSUE TITLE
RC for GERB

### ISSUE THREAD

**Issue by gerbteam** [PCMDI/obs4MIPs-cmor-tables#254]
The GERB Team at Imperial College would like to update the version of the GERB obs4MIPs products submitted to obs4MIPs in May 2020. These data are the "rlut" and "rsut" quantities (e.g. "rlut_1hrCM_GERB-HR-ED01-1-0_BE_gn_200701-200712.nc", "rsut_1hrCM_GERB-HR-ED01-1-0_BE_gn_200701-200712.nc", etc.). 

Extensive effort has been made to increase the amount of data made available and to reduce uncertainties in the data set where data are missing in the GERB Edition 1 high resolution (HR) products. 

Updated Tech Notes are being prepared to accompany the improved data records which we would like to submit to the obs4MIPs archive.

The core source data remain unchanged, these are the GERB HR Edition 1 ("ED01") data. Therefore we seek advice on how best to define the updated version of the product prepared for obs4MIPs.

We would like to propose the following changes from the original submission:
source = 'GERB HR_ED01_1.1 (2018): Geostationary Earth Radiation Budget'
source_id = 'GERB-HR-ED01-1-1'
source_version_number = 'HR_ED01_1.1'

The original submission equivalent parameters are set out below for reference:
source = 'GERB HR_ED01_1.0 (2018): Geostationary Earth Radiation Budget'
source_id = 'GERB-HR-ED01-1-0'
source_version_number = 'HR_ED01_1.0'

Please let us know if the revised values for the 3 fields are acceptable and sufficient to distinguish our updated products from the original obs4MIPs submission and whether the information provided here is sufficient for you to update the required tables and definitions for GERB.

We would also like to understand whether the current GERB obs4MIPs data will co-exist alongside our proposed improved version, or whether the earlier version will be removed to avoid user confusion.

A timely response would be appreciated.
Best wishes,
Rich (on behalf of the GERB Team at Imperial College London). 

________________________________________________________________________________________________________
The following are required registered content (with example content for each item in **bold**). Please replace the example text below with your information to the right of the equal sign (DO NOT MAKE ANY CHANGES TO THE LEFT HAND SIDE OF THE EQUAL SIGN):
1) source_id['source_id'][key][**'source_name'**] = 'GPCP'
2) source_id['source_id'][key][**'release_year'**] = '2011'
3) source_id['source_id'][key][**'source_description'**] = 'Global Precipitation Climatology Project'
4) source_id['source_id'][key][**'source_version_number'**] = '2.3'
5) source_id['source_id'][key][**'institution_id'**] = 'UofMD'
6) source_id['source_id'][key][**'region'**] = 'global'
7) source_id['source_id'][key][**'source_type'**] = 'satellite_merged'
8) A list of CMIP variable_ids that the above information refers to.  In most cases it will only be for one variable_id.  If it is for more than one, please make sure your source_description is sufficiently general to apply to all relevant variable_ids.

________________________________________________________________________________________________________

See note 14 and Appendix II of the obs4MIPs data specifications (https://goo.gl/jVZsQl) for more information regarding registered content, and feel free to ask questions!

**Comment by gleckler1** [comment]
Hello Rich and GerbTeam, and congratulations on your updated products.  We have [updated the obs4MIPs list of source_ids](https://esgf-node.llnl.gov/esgf-idp/openid/gleckler1) to include GERB-HR-ED01-1-1.   You mention 3 fields, but we are only aware of 2 (rlut and rsut).   Are we missing something?   Your question regarding older versions is a good one.  Generally we prefer to keep legacy products available to ensure reproducibility, and we are working to make the "latest" version more prominent.  These data remain something of a special case as the time sampling does not align with CMIP time series, but we do think it is important to make them available.   Please don't hesitate to ask if you have any questions.

**Comment by gerbteam** [comment]
Hi @gleckler1 thanks very much for confirming the updated list of source_ids. The 3 fields I mentioned referred to the "source", "source_id" and "source_version_number". You are correct, we only produce two variables "rlut" and "rsut". Thank you also for confirming that the older version will remain visible - this is fine of course, although we would hope that users will use the updated version. Updated tech notes will of course be made available describing the improvements made to our latest version of the GERB obs4MIPs products.

Many thanks,
Rich (on behalf of the GERB Team)
