### ISSUE TITLE
IMERG @ RSS

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/obs4MIPs-cmor-tables#255]

**Comment by gleckler1** [comment]
@manaster cdms imerge codes now in master.  Go ahead and create a new 255 branch for converting to xcdat and I'll remove the branch 255_pjg-amw_imergRSS

**Comment by manaster** [comment]
@gleckler1 great!  Just created a new '255' branch.

**Comment by manaster** [comment]
@gleckler1 looks like you will likely need to merge the current '255_aim_imergxcdat' into the 'master' to get all of the appropriate IMERG code (along with relevant RSS upper atmosphere code) onto the 'master' branch.  Once you do that, I can go ahead and create a new '255' branch that I can use for IMERG V7 work and delete the old '255' branch.  

I just rebased the current '255_aim_imergxcdat' branch, so you should be able to merge it.  I will create a pull request now.
