### ISSUE TITLE
Need tables for daily precipitation flux dataset

### ISSUE THREAD

**Issue by JimBiardCics** [PCMDI/obs4MIPs-cmor-tables#30]
We have a precipitation flux dataset (from PERSIANN) that contains whole-globe information with daily time resolution. We need tables to support this. The variable is 'pr'. This dataset is on a 0.25 x 0.25 degree lat/lon grid (covered in another issue).

**Comment by gleckler1** [comment]
@JimBiardCics  This should be a straightforward carry over from CMIP6.   We'll let you know when the table is ready.

**Comment by durack1** [comment]
@JimBiardCics @gleckler1 this should be fixed by #34
