### ISSUE TITLE
Add ancillary variables to tables (Std Dev, NObs, etc.)

### ISSUE THREAD

**Issue by scott-stevens** [PCMDI/obs4MIPs-cmor-tables#50]
We are doing daily -> monthly time-averaging for a number of our variables (NDVI, FAPAR, LAI, etc.), and we understand that we will need to generate ancillary files for each of those (NObs, Std Dev, Std Err), and that all of those individual "variables" (NDVI_Nobs, NDVI_StdDev, etc.) will need to be added to the tables.  

We figured we'd get the ball rolling on those.  Thanks!

**Comment by gleckler1** [comment]
@scott-stevens  Yes, these will need to be added to the tables.   Traveling home now and will be working on obs4MIPs much of next week.

**Comment by scott-stevens** [comment]
Is there a current status on all of these ancillary variables and how they're to be included?

**Comment by taylor13** [comment]
We will generate separate tables for monNobs and monStderr, and we'll get back to you shortly with the details.

**Comment by Funkensieper** [comment]
We have lots of nobs/stddevs to register, too. Can I add them here or should I open a separate issue?

**Comment by durack1** [comment]
@Funkensieper we're just trying to finalize the format of these two new tables, and once we have this in place, we can start filling up the tables with all the additional variables required

@scott-stevens @JimBiardCics we'll also need to engage with you guys to make sure we have all these new variables defined.. Will ping you all when we have the template in place

@taylor13 @gleckler1 pinging you both here

**Comment by JimBiardCics** [comment]
@durack1 Excellent! I assume you will also have wonderful information on how these are clearly tied to their parent variables. I look forward to it!

**Comment by taylor13** [comment]
That should be obvious because they will share a common source and the variable names will include the name of the variable (e.g., for a variable named "ta",  the corresponding variable names for the statistics will be "taNobs" and "taStderr".    Right @gleckler1 and @durack1 ???

**Comment by taylor13** [comment]
in the Stderr table:  long_name should be "Normalized Difference Vegetation Index Standard Error"  (i.e., same as ndvi variable, but with "Standard Error" appended.

also, units should be "1", I think.
we should also consider a "cell_methods", but probably o.k. as is.

in the Nobs table:  long_name should be modified similar to above.
Also "type": "integer" , I think.

**Comment by JimBiardCics** [comment]
By the way, the CF for standard error is to add a space-separated modifier to the standard name. For air_temperature, it would be "air_temperature standard_error". This does not require a new standard name to be requested. Standard deviation is indicated in a cell_methods attribute. For example, cell_methods = "time: standard_deviation". The standard name for a standard deviation is the same as for the primary variable. The number of observations is handled the same way that standard error is. It is indicated via a modification to the standard name, so "air_temperature number_of_observations". See [CF Conventions Appendix C](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#standard-name-modifiers).

**Comment by durack1** [comment]
@JimBiardCics we need to ensure that each filename is unique, so that we don't get filename clashes during file creation as both the primary variable along with it's stats fields will share the same DRS (directory structure) - a changed standard_name in the file metadata won't cut it

**Comment by JimBiardCics** [comment]
@durack1 It's fine to have a different variable name. What I was describing was how, from a CF perspective, a variable is marked as being a standard error, a standard deviation, or a number of observations. I have assumed from what I've read in the new tables files that we will have unique variable names for each ancillary variable.

**Comment by durack1** [comment]
@JimBiardCics yep exactly, you'll see that the new nvdiStderr does indeed follow the CF protocol - [PCMDI/obs4MIPs-cmor-tables/Tables/obs4MIPs_monStderr.json](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/Tables/obs4MIPs_monStderr.json#L24)

We're looking forward to you folks testing the new specs out with some real-world cases, just to make sure that the assumptions that we've made with the ODS-2.1 update can deal with them all

**Comment by durack1** [comment]
@JimBiardCics @Funkensieper @scott-stevens we now include both [Tables/obs4MIPs_monStderr.json](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/Tables/obs4MIPs_monStderr.json) and [Tables/obs4MIPs_monNobs.json](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/Tables/obs4MIPs_monNobs.json), so can we close out this issue?

**Comment by gleckler1** [comment]
@JimBiardCics @Funkensieper @scott-stevens 
@durack1 I think so but I need to relay the solution being discussed with regards to these ancillary files.

**Comment by durack1** [comment]
@gleckler1 will close, if we need to continue this discussion lets direct comments into #123
