### ISSUE TITLE
ODS 2.x review

### ISSUE THREAD

**Issue by Funkensieper** [PCMDI/obs4MIPs-cmor-tables#53]
I just reviewed the latest ODS version (July 17) as well as the corresponding tables and have some questions/comments (I already sent some of them to @gleckler1, but maybe they got lost):

1. Note 6: Remove dataset_version_number as it is now included in source_id? Or use source_label instead of source_id?
2. grid_label: Is it "gr[i]" as described in the table or "g[i]" as described in Note 8?
3. mip_era: In the ODS this is fixed to "obs4MIPs", but in the json tables it is "CMIP5/6". Which one is correct?
4. source_id: According to the ODS, source_id must include the version number. Does that mean a user has to register a separate source for each dataset version?
5. source_version_number is missing in the ODS global attributes table
6. ncdump of example file should be updated
7. Filename: Remove source_version_number as it is already included in source_id? Or use source_label instead of source_id?

**Comment by gleckler1** [comment]
Thanks for the feedback Stephan, this is very helpful.

I have just changed Note 4[6-revised], replacing “dataset_version_number” with “source_label”

g[i] in table 8 changed to gr[i]

We may need another 1-2 days to finalize use (or not) of mip_era

source_id: According to the ODS, source_id must include the version number. Does that mean a user has to register a separate source for each dataset version?
                Good question.   I think registering the source_label may be adequate, but let me get back to you in 1-2 days

source_version_number has been removed, and now included in source_id (with character restrictions) and in the source (without restrictions).   But we will discuss this again and … get back to you in 1-2 days

ndump example was just updated but will continue to need finessing

source_version_number removed from filename, replaced with source_id


We will get back to you shortly.   Many thanks again!

Peter

**Comment by durack1** [comment]
@gleckler1 @Funkensieper it makes sense that all these loose ends are fixed along with the required changes in #54, if any other tweaks are required append them here and we can solve both issues at once

**Comment by Funkensieper** [comment]
Happy to help :) I checked out the most recent tables with CMOR-3.2.5. This is what I found:
- ``src/writeJson.py`` erroneously adds an extra level to the CV dictionary preventing CMOR from validating the attributes. The fix is just one line, I will send a PR so you can review it.
- I also removed ``source_version_number`` from the required global attributes
- ``source_id`` is not validated by CMOR (maybe due to the nested dictionary in the CV?)
- Is there a way to make CMOR validate optional attributes (such as ``region``)? Currently they are not recognized because they are not listed in the required global attribtues.
- I manually added ``int_missing_value=-2^31`` to the table (see #18)

You can checkout the reformatted dataset here: ftp://ftp-cmsaf.dwd.de/sfinkens/obs4mips/

**Comment by taylor13** [comment]
@Funkensieper 
concerning mip_era, Peter and I discussed this and plan to eliminate it (irrelevant to obs4MIPs).

 concerning registration, I think we'll need to register each source_id, not just source_label.  (Do you expect to generate many different versions over the next few years, say?)

For planned changes to the obs4MIPs_CVs and obs4MIPs_input, see: https://github.com/PCMDI/obs4MIPs-cmor-tables/issues/57, https://github.com/PCMDI/obs4MIPs-cmor-tables/issues/58, and https://github.com/PCMDI/obs4MIPs-cmor-tables/issues/59 .   Once implemented I think we'll be in pretty good shape.

thanks for your help with this.

**Comment by Funkensieper** [comment]
Looks good to me! Concerning the registration, that was just a general question. Our release cycle is 2-4 years.
