### ISSUE TITLE
output_path_template and output_file_template are reversed in the demo

### ISSUE THREAD

**Issue by durack1** [PCMDI/obs4MIPs-cmor-tables#54]
These are inverted, compared to the [google doc](https://docs.google.com/document/d/1FXXBhUh71Hjus557ZTD3EKPi_2zxeLvi1aICXOjVYPc/edit#heading=h.1t3h5sf)
```
"output_path_template": "<variable_id><table_id><source_id><variant_label><grid_label><version>",
"output_file_template": "<activity_id><institution_id><source_id><table_id><variable_id><grid_label>",
```
This should be
```
"output_path_template": "<activity_id><institution_id><source_id><table_id><variable_id><grid_label><version>",
"output_file_template": "<variable_id>_<table_id>_<source_id>_<variant_label>_<grid_label>[_<time_range>].nc",
```

**Comment by durack1** [comment]
@gleckler1 @taylor13 pinging you both here.

Following the email and in-house discussion this morning, we also need to amend the following:
```
"further_info_url": "https://www.earthsystemcog.org/projects/obs4mips/",
```
to:
```
"further_info_url": "http://furtherinfo.es-doc.org/obs4MIPs.<institution_id>.<source_id>.<variable_id>.<variant_label>",
```
`source_label` also needs to be added, for the demo this is `REMSS-PRW`. This means your `source_id` (generated by merging the `source_label` and the user provided version identifier) becomes `REMSS-PRW-6-6-0`

I think it's insightful to look at the entries in [demo/rssSsmiPrw-input.json](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/demo/rssSsmiPrw-input.json) as some of these user-provided entries are indeed redundant, there may also be missing pieces..

**Comment by gleckler1** [comment]
@durack1 @taylor13  It seems to me variant_label is not req'd because 99% of the time its going to be 'BE'.   I think any documentation on the 'BE' would include and variants, if they exist.   But I'm not familiar with the level of granularity with ESDocs

**Comment by durack1** [comment]
@Funkensieper it would be useful to get your perspective as we iterate to the final specs.. If you had one or two "demo" datasets that we could see how the files (and directory structure) look once they are pushed through it would be very helpful.

**Comment by gleckler1** [comment]
@durack1 created branch swapped output filename and path but experienced writejson error:
tableName: SImon
tableName: Aday
File existing, purging: ../Tables/obs4MIPs_Aday.json
File existing, purging: ../Tables/obs4MIPs_Amon.json
File existing, purging: ../Tables/obs4MIPs_Lmon.json
File existing, purging: ../Tables/obs4MIPs_Omon.json
File existing, purging: ../Tables/obs4MIPs_SImon.json
File existing, purging: ../Tables/obs4MIPs_fx.json
File existing, purging: ../obs4MIPs_coordinate.json
File existing, purging: ../obs4MIPs_formula_terms.json
File existing, purging: ../obs4MIPs_frequency.json
File existing, purging: ../obs4MIPs_grid_label.json
File existing, purging: ../obs4MIPs_grids.json
File existing, purging: ../obs4MIPs_institution_id.json
File existing, purging: ../obs4MIPs_license.json
File existing, purging: ../obs4MIPs_mip_era.json
File existing, purging: ../obs4MIPs_nominal_resolution.json
File existing, purging: ../obs4MIPs_product.json
File existing, purging: ../obs4MIPs_realm.json
File existing, purging: ../obs4MIPs_region.json
File existing, purging: ../obs4MIPs_required_global_attributes.json
File existing, purging: ../obs4MIPs_source_id.json
File existing, purging: ../obs4MIPs_source_type.json
File existing, purging: ../obs4MIPs_table_id.json
File existing, purging: obs4MIPs_CV.json
Traceback (most recent call last):
  File "writeJson.py", line 683, in <module>
    cwd=os.getcwd())
  File "/export/gleckler1/miniconda2/envs/CMORjuly7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/export/gleckler1/miniconda2/envs/CMORjuly7/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception

**Comment by durack1** [comment]
@gleckler1 you've hit an issue writing the demo.zip, you need 7za installed.. Will sort this out tomorrow

**Comment by durack1** [comment]
The tracking_id prefix might be something else we need to tweak, following this email discussion:
```
From: Karl Taylor
Date: Saturday, July 1, 2017 at 8:00 AM
To: "wgcm-wip"
Cc: "Gleckler, Peter J.", Tobias Weigel
Subject: Re: AW: tracking_id

Thanks Martin and Michael for the quick responses.  

I think it's probably a good idea, as you say, to be able to distinguish obs4MIPs from CMIP with a different prefix.   

I know there is a group in Europe (ESSA, I think) ready to write some obs4MIPs files, so as soon as you have assigned the new handle, please let us know.

best regards,
Karl

On 7/1/17 12:41 AM, Michael Lautenschlager wrote:
Hello all,
yes, Martin us right, we can use the same prefix for obs4mips as for CMIP6. There is no technical problem. My idea is that we choose for obs4mips a different prefix to separate data sources. I add Tobias in CC that he can respond on Monday and assign a prefix for obs4mips if possible with respect to CMOR.
Best regards, Michael 
 
---------------
Dr. Michael Lautenschlager
Abteilungsleiter Datenmanagement
World Data Center for Climate (WDCC)

Deutsches Klimarechenzentrum GmbH (DKRZ)
Bundesstraße 45a * D-20146 Hamburg * Germany

Phone: +49 40 460094-118
Email: lautenschlager
URL: www.dkrz.de

Geschäftsführer: Prof. Dr. Thomas Ludwig
Sitz der Gesellschaft: Hamburg
Amtsgericht Hamburg HRB 39784 
 
Von: martin.juckes
Gesendet: Samstag, 1. Juli 2017 08:40
An: taylor13; wgcm-wip; lautenschlager
Cc: gleckler1
Betreff: RE: tracking_id
 
Hello All,
 
I think this is a question for Michael: "hdl:21.14100/....." is a service maintained by DKRZ: in principle it could be extended to cover OBS4MIP, but finding the resources to run the service may be another question,
 
regards,
Martin
________________________________
From: Karl Taylor
Sent: 30 June 2017 22:38
To: WIP List
Cc: Peter Gleckler
Subject: tracking_id
 
Hi Eric and all,
 
In CMIP6 the tracking i.d.s for individual files are defined as:

tracking_id should be of the form hdl:21.14100/<uuid>  (e.g., “hdl:21.14100/02d9e6d5-9467-382e-8f9b-9300a64ac3cd”).  The tracking_id should be unique for each file published in ESGF.   CMOR automatically generates a tracking_id
 
My question is can we use this same form for obs4MIPs files, or should they be assigned a different prefix "handle" (hdl number)?

thanks,
 
Karl
```

**Comment by taylor13** [comment]
got this email on 7/4/17:

Hello Karl,

we have set things in motion to register the new prefix "21.14102" and
are restructuring the RabbitMQ queueing mechanics so that both cmip6 and
obs4mips Handles can be registered in parallel.

However, the whole workflow depends also on the new ESGF release as the
integration of the new prefix requires software changes that are
currently not deployed in the publisher (the publisher needs to know
about the new queueing structure). Naturally, all files must bear the
new prefix in their headers, which requires CMOR to be configured via
its JSON files for the new prefix for obs4mips specifically, but not
modified in source code.

Best, Tobias
