### ISSUE TITLE
package distributed to the community should not use horrendous package aliases

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/obs4MIPs-cmor-tables#56]
for example: 
https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/demo/runCmorDemo.py#L2

it probably should be pep8ed and flake8ed as well.

**Comment by dnadeau4** [comment]
Problem arise here.
https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/demo/runCmorDemo.py#L22

**Comment by gleckler1** [comment]
@doutriaux1  @dnadeau4  Any specific improvements you recommend are welcome, best if you provide a pull request with them.

**Comment by durack1** [comment]
@doutriaux1 is `import cdms2 as cdm` really worthy of a **horrendous** tag?

**Comment by durack1** [comment]
@doutriaux1 @dnadeau4 your silence is taken as an implicit endorsement for 3 letter import statements, so I will close
