### ISSUE TITLE
source_id problems

### ISSUE THREAD

**Issue by Funkensieper** [PCMDI/obs4MIPs-cmor-tables#64]
I still have some problems with the ``source_id`` attribute (using the latest CMOR 3.2.6):

1. ``source_id`` is not validated by CMOR
2. ``src/writeJson.py`` does not include ``source_label`` and ``source_type`` defined within the ``source_id`` compound into the CV. I would suggest adding the following lines [here](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/src/writeJson.py#L668)

        obs4MIPs_CV['CV']['source_id'][key]['source_label'] = source_id_[key]['source_label']
        obs4MIPs_CV['CV']['source_id'][key]['source_type'] = source_id_[key]['source_type']
3. Even if I manually add ``source_type`` and ``source_label`` to the CV,

            "source_id":{
                "REMSS-PRW-6-6-0":{
                    "source":"REMSS PRW v6.6.0 (2017): Precipitable Water",
                    "source_label":"REMSS-PRW",
                    "source_type":"satellite_blended"
                }
            },

  CMOR doesn't recognize them.

**Comment by durack1** [comment]
@Funkensieper thanks for pointing this out. For obs4MIPs we have limited the amount of validation and `source_id` is excluded, which is very different to CMIP6.

We'll have a think about this and get back to you.

@gleckler1 @taylor13 pinging you both here

**Comment by JimBiardCics** [comment]
@durack1 @gleckler1 @taylor13 I have a related question. How are you expecting the new source fields to be specified, and what are the valid values for them? We just updated from github, and found that there are a number of new fields that are expected, source_label and source_type among them.

**Comment by durack1** [comment]
@JimBiardCics the registration info should follow the example in the PR #65 [`obs4MIPs_source_id.json`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/4c15a52774b9c6fbc2f89ce53f67821671c0c5a8/obs4MIPs_source_id.json). Of these fields [`institution_id`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/obs4MIPs_institution_id.json), [`region`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/obs4MIPs_region.json) and [`source_type`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/obs4MIPs_source_type.json) are controlled vocabulary that are contained in the other files

**Comment by JimBiardCics** [comment]
@durack1 @gleckler1 I'm sorry that I keep pestering you. With the advent of the source block in the obs4MIPs_CV.json file, do I need to specify any of these in my runtime CMOR config file, or will they be pulled in based on the value of source_id in my config file?

- source
- source_label
- source_type
- region

**Comment by durack1** [comment]
@JimBiardCics no you're not, you love pestering!! In theory, yep that's exactly what will happen, however CMOR is currently hard-coded to deal with the CMIP6 source_id, so as it's not implemented it won't be validated.. With the current [`nightly` release of CMOR](https://anaconda.org/PCMDI/cmor/files) you should be able to create whatever you like in your input json (e.g. [`demo/rssSsmiPrw-input.json`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/demo/rssSsmiPrw-input.json)) and it will be written.. In the upcoming release these values will be validated against the registered content

**Comment by JimBiardCics** [comment]
@durack1 So if I only specify source_id, the other four attributes will be pulled in / generated by CMOR? Does this go for institution_id and institution as well? If I only specify institution_id, will CMOR pull in institution from the tables?

**Comment by durack1** [comment]
@JimBiardCics that's exactly how it's meant to work (with `source_id` not yet implemented, waiting for CMOR 3.2.6), if you want to test to make sure it works be my guest, it'd be great to triple check it's functioning as expected
