### ISSUE TITLE
Where can I find a list of which JSON files need to be incorporated into the obs4MIPs_CV.json file?

### ISSUE THREAD

**Issue by JimBiardCics** [PCMDI/obs4MIPs-cmor-tables#67]
@durack1 @gleckler1 The files to be incorporated into the obs4MIPs_CV.json file is in flux, and I don't see a clear way to tell what should be included.

**Comment by JimBiardCics** [comment]
@durack1 So, you are building the obs4MIPs_CV.json file under the covers now? Because I don't see anything in the demo that would build it.

**Comment by durack1** [comment]
@JimBiardCics correct, it's all built in the [`src/writeJson.py`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/src/writeJson.py#L655-L693) file

**Comment by JimBiardCics** [comment]
@durack1 Is this something that will be clear once CMOR 3.2.6 is available on conda? Or do I now need to run writeJson.py? Because I don't see any way for the current system to know where all of the files that go into the obs4MIPs_CV.json file are located.

**Comment by durack1** [comment]
@JimBiardCics sorry, I'm obviously not being clear, I will try again. From an obs4MIPs user point of you you need to complete the following steps:
1. Register your `institution_id` (following examples in [`obs4MIPs_institution_id.json`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/obs4MIPs_institution_id.json)
2. Register your `source_id` [`obs4MIPs_source_id.json`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/obs4MIPs_source_id.json)

Once you have done these, and they are registered entries, you download the [`demo/demo.zip`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/demo/demo.zip) file. Once you unzip this file you will have all the files contained in that directory:
```
Tables (directory containing all table files, with added obs4MIPs-specific variables)
obs4MIPs_CV.json
rssSsmiPrw-input.json <- User edits required
rss_ssmi_prw_v06.6-demo.nc <- example file, user file required
runCmorDemo.py <- User edits required
```
If you make edits to the files noted above, and edit `runCmorDemo.py` to point to your ['inputDataPath`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/demo/runCmorDemo.py#L9) then you should have a nice new CMORized file after a couple of seconds..

Is that clearer?

**Comment by gleckler1** [comment]
@JimBiardCics @durack1   In addition to the institution_id and source_id, institution, source and source_label constitute "registered content"... the template for submitting registered content is in the process of being updated:  https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/pjg_70_regcontent_template/.github/ISSUE_TEMPLATE.md

**Comment by durack1** [comment]
@gleckler1 @JimBiardCics just to be clear, the current PR #65 provides examples of the input [`obs4MIPs_source_id.json`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/issue64_durack1_source_idAndCVCleanup/obs4MIPs_source_id.json#L3-L11) and the output [`demo/obs4MIPs_CV.json`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/issue64_durack1_source_idAndCVCleanup/demo/obs4MIPs_CV.json#L198-L204) where `source_id` is managed, and included in the demo for folks to use.

To summarize, the registered content in `obs4MIPs_source_id.json` looks like:
```
    "source_id":{
        "REMSS-PRW-6-6-0":{
            "description":"Precipitable Water",
            "institution_id":"RSS",
            "label":"REMSS PRW 6.6.0",
            "region":"global",
            "release_year":"2017",
            "source_id":"REMSS-PRW-6-6-0",
            "source_label":"REMSS-PRW",
            "source_type":"satellite_blended"
        }
    }
```
And once magic happens (registered components are concatenated), we then get the following (below) contained in `demo/obs4MIPs_CV.json`:
```
        "source_id":{
            "REMSS-PRW-6-6-0":{
                "source":"REMSS PRW 6.6.0 (2017): Precipitable Water",
                "source_label":"REMSS-PRW",
                "source_type":"satellite_blended"
            }
        },
```
The entry directly above (`demo/obs4MIPs_CV.json`) will then be used, and validated by CMOR, with the following summarized entries written to output files

**Comment by gleckler1** [comment]
@durack1 the problem these nice improvements is that they have kept us in a holding pattern, losing over a month of CMOR etc not being ready for use

**Comment by JimBiardCics** [comment]
@durack1 @gleckler1 We aren't using the demo code to generate our files. We have our own app based on cdms2, cdtime, and cmor. Since the obs4MIPs_CV.json file isn't in the github repository, how am I to keep it up to date? Are you constantly updating the demo.zip file?

**Comment by doutriaux1** [comment]
@durack1 see... You should make this a package, this demo.zip is causing troubles :wink:

**Comment by durack1** [comment]
@JimBiardCics yep the [`demo/obs4MIPs_CV.json`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/demo/obs4MIPs_CV.json) is in the repo and always being kept up-to-date - the demo.zip is also always being updated to contain everything (apart from itself) in the demo subdir

**Comment by JimBiardCics** [comment]
@durack1 Ah. So demo/obs4MIPs_CV.json is now kept up to date. Thanks for taking the time to help me understand! I gotta agree with @doutriaux1 - seems like the obs4MIPs-cmor-tables (san demo) with all files in proper relative locations should be a standalone package of some sort.

**Comment by durack1** [comment]
@JimBiardCics the issue with the demo is that a user needs to know where at least 2 of the files are, as they actively need to edit these to make the software write their data. A conda package would be a great way to distribute the static pieces (Tables and other jsons) that CMOR needs, but would hide the json input files that a user needs to edit.. So I'm thinking that having the zip archive is a clean way to distribute all the pieces.. With the caveat that a user will have to use conda to install CMOR to their machine locally anyway..

Happy to hear opinions on this.. But there's no time allocated to support this process, so a shorter path to the end is better than one that wanders all over the place

**Comment by JimBiardCics** [comment]
@gleckler1 @durack1 I looked at the draft template for registered content that Peter mentioned. I noticed that the block of JSON has a 'label' field with contents that appears to match what I would expect for the 'source' field, and has no 'source' field.

**Comment by durack1** [comment]
@JimBiardCics the `source` entry is generated automatically (in [`src/writeJson.py`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/src/writeJson.py#L665-L668) from the registered components. It combines the `label` (`release_year`): `description` fields

**Comment by JimBiardCics** [comment]
@durack1 @doutriaux1 @gleckler1 The two runtime config files are, in my mind, quite different from the files in the Tables folder and the obs4MIPs_CV.json file. I, as a regular user, shouldn't ever touch those. It seems to me that the simple solution would be, at minimum, to put the obs4MIPs_CV.json file into the top level folder of the repository. The ideal, from my perspective, would be to put all the needed files into the top-level Tables folder. As near as I can tell, that would be:
```
obs4MIPs_Aday.json
obs4MIPs_Amon.json
obs4MIPs_Lmon.json
obs4MIPs_Omon.json
obs4MIPs_SImon.json
obs4MIPs_coordinate.json
obs4MIPs_formula_terms.json
obs4MIPs_Amon.json
obs4MIPs_fx.json
obs4MIPs_grids.json
obs4MIPs_CV.json
```

**Comment by JimBiardCics** [comment]
@durack1 RE: source entry. OK. So label is the 'with spaces' version of source_label, right? No, wait, it's what used to be the source, with spaces and a version, right? And you guys fold that into a source key dynamically in the CMOR code. So the definitions are:
```
label = Free text source name with spaces and version info.
source_id = Label with all non-alphanumeric characters converted to dashes (approximately).
source_label = source_id with version info removed.
```
Is that right?

**Comment by durack1** [comment]
@JimBiardCics the required files are:
```
obs4MIPs_CV.json
rssSsmiPrw-input.json <- User must edit
rss_ssmi_prw_v06.6-demo.nc <- Use must provide
runCmorDemo.py <- User must edit
Tables/obs4MIPs_Aday.json
Tables/obs4MIPs_Amon.json
Tables/obs4MIPs_Lmon.json
Tables/obs4MIPs_Omon.json
Tables/obs4MIPs_SImon.json
Tables/obs4MIPs_coordinate.json
Tables/obs4MIPs_formula_terms.json
Tables/obs4MIPs_fx.json
Tables/obs4MIPs_grids.json
```
And these are all included in the `demo` subdir, along with the `demo.zip` copy of the same. To me this is pretty clean, particularly if a novice user was pointed to download the zip archive after installing CMOR via conda..

**Comment by durack1** [comment]
@JimBiardCics RE source_id, the registered content (from [`source_id`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/4c15a52774b9c6fbc2f89ce53f67821671c0c5a8/obs4MIPs_source_id.json):
```json
    "source_id":{
        "REMSS-PRW-6-6-0":{
            "description":"Precipitable Water",
            "institution_id":"RSS",
            "label":"REMSS PRW 6.6.0",
            "region":"global",
            "release_year":"2017",
            "source_id":"REMSS-PRW-6-6-0",
            "source_label":"REMSS-PRW",
            "source_type":"satellite_blended"
        }
}
```
then becomes the following entry in [`obs4MIPs_CV.json`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/4c15a52774b9c6fbc2f89ce53f67821671c0c5a8/demo/obs4MIPs_CV.json#L198-L204)
```
        "source_id":{
            "REMSS-PRW-6-6-0":{
                "source":"REMSS PRW 6.6.0 (2017): Precipitable Water",
                "source_label":"REMSS-PRW",
                "source_type":"satellite_blended"
            }
},
```

**Comment by JimBiardCics** [comment]
@durack1 @gleckler1 @doutriaux1 I appreciate that I no longer have to build the obs4MIPs_CV.json file myself. I get having the demo folder. I _don't_ get not having the primary output content for your repository at the top level. Now that I know how to proceed, I'll be OK, but I would never ever assume that the demo folder was where I needed to go for the release files for this repository. I'll hush after this message, but I'd suggest a structure along the lines of:
```
README.md
Tables
    obs4MIPs_Aday.json
    obs4MIPs_Amon.json
    obs4MIPs_Lmon.json
    obs4MIPs_Omon.json
    obs4MIPs_SImon.json
    obs4MIPs_coordinate.json
    obs4MIPs_formula_terms.json
    obs4MIPs_fx.json
    obs4MIPs_grids.json
    obs4MIPs_CV.json
demo
    (Whatever you like for a working demo.)
src
    (writeJson.py and any input files needed to make the files in Tables.)
```

**Comment by taylor13** [comment]
From someone on the fringes (me), that organization does have some appeal, but perhaps there are reasons to have a flat structure??
Karl

**Comment by durack1** [comment]
@JimBiardCics @taylor13 the structure suggested [above](https://github.com/PCMDI/obs4MIPs-cmor-tables/issues/67#issuecomment-322539193) is actually identical to what is included in the [`demo`](https://github.com/PCMDI/obs4MIPs-cmor-tables/tree/master/demo) subdirectory, apart from the `obs4MIPs_CV.json` file not being included in the `Tables` subdir, as it's not a table file (the rest are)

@JimBiardCics your point about `coordinate`, `formula_terms` and `grids` is a reasonable one, as these are downstream "Table" files from [PCMDI/cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables/tree/master/Tables), same at the `Aday`, `Amon` etc

**Comment by durack1** [comment]
Reopening to deal with this reorg

**Comment by durack1** [comment]
@JimBiardCics @gleckler1 @taylor13 @doutriaux1 the reorg discussed in considerable length is now in place in #78 or you can view the directory structure at https://github.com/PCMDI/obs4MIPs-cmor-tables/tree/issue67_durack1_RepoReorg (vs [master](https://github.com/PCMDI/obs4MIPs-cmor-tables/tree/master))

I'll wait overnight for any complaints/comments and merge this in tomorrow
