### ISSUE TITLE
If I have registered my source, is source_id all I need to include in my CMOR_config.json file?

### ISSUE THREAD

**Issue by JimBiardCics** [PCMDI/obs4MIPs-cmor-tables#69]
@durack1 If I have registered my source, is source_id all I need to include in my CMOR_config.json file?

**Comment by durack1** [comment]
@JimBiardCics yes exactly, once the changes planned for `CMOR 3.2.6` land, the PR https://github.com/PCMDI/obs4MIPs-cmor-tables/pull/65 can be merged and all you'll need to do is indicate your `source_id` and the information will be pulled from the registered information included in the `obs4MIPs_CV.json`
