### ISSUE TITLE
update template for "registering content" with new issue

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/obs4MIPs-cmor-tables#70]
@durack1  Need to provide examples of all registered content in https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by JimBiardCics** [comment]
@gleckler1 @durack1 Regarding the source_id registration. Do you see this as being one-to-one with datasets? We have three datasets (NDVI, LAI, and FAPAR) that come from the same package - the "Veggie Bundle" CDR. We're good either way, we just want to get a handle on this.

**Comment by gleckler1** [comment]
@JimBiardCics @durack1   I think you are suggesting that in this "veggie" case if the NDVI data is updated, by definition so will LAI and FAPAR....   So,  for example NDVI-2-0 implies LAI-2-0, and FAPAR-2-0, and if one gets updated to 2.1 so do the other two.   The key thing is that we need to be able to keep track of versions of each dataset.  Its not a problem if the versions are identical, but we need a version.    Make any sense?

**Comment by JimBiardCics** [comment]
@gleckler1 @durack1 So the source group is more about the source dataset, as opposed to the source for the data in the original dataset, is that right?

**Comment by durack1** [comment]
@gleckler1 you're the v1 vs v2 fella, so over to you..

**Comment by gleckler1** [comment]
@JimBiardCics @durack1  new issue template should help clarify but let us know if not
