### ISSUE TITLE
source_id registration of AVHRR-Land_NDVI_AVH13C1.v4r0

### ISSUE THREAD

**Issue by scott-stevens** [PCMDI/obs4MIPs-cmor-tables#73]
source_id: AVHRR-Land_NDVI_AVH13C1.v4r0
description: Normalized Difference Vegetation Index
institution_id: NOAA-NCEI
label: NDVI V4.0
region: global_land
source_label: AVHRR-NDVI
source_type: satellite

Comments:  Is there a controlled list of source_type somewhere?  The only example I see in the obs4mips tables so far is satellite_blended.

**Comment by durack1** [comment]
@scott-stevens the listings of `source_type` can be found in [PCMDI/obs4MIPs-cmor-tables/master/obs4MIPs_source_type.json](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/obs4MIPs_source_type.json)

**Comment by scott-stevens** [comment]
Wonderful, thank you.  I'll check with the dataset creator and update this accordingly once I hear back.

**Comment by scott-stevens** [comment]
@durack1 Here is the updated information for AVHRR-NDVI-4-0

source_id: AVHRR-NDVI-4-0
description: Normalized Difference Vegetation Index
institution_id: NOAA-NCEI
label: NDVI V4.0
region: global_land
release_year: 2013
source_label: AVHRR-NDVI
source_type: satellite_retrieval

Thank you!

**Comment by durack1** [comment]
@scott-stevens can you review this registration against the other [`NOAA-NCEI registrations`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/obs4MIPs_source_id.json#L64-L163) and let us know if any tweaks are required?

If you're happy with this, then we can close out this issue

**Comment by scott-stevens** [comment]
@durack1 This one looks just fine.  The others were modeled after it, so it matches up nicely.  No tweaks necessary.

**Comment by durack1** [comment]
@scott-stevens great, thanks for closing
