### ISSUE TITLE
variant_label for obs4MIPS datasets

### ISSUE THREAD

**Issue by scott-stevens** [PCMDI/obs4MIPs-cmor-tables#74]
Is variant_label still a required attribute for obs4MIPs datasets?  From the documentation, it seems specific to model output.

**Comment by taylor13** [comment]
Yes it is required.  See  https://goo.gl/jVZsQl which indicates that for obs4MIPs it often will be assigned the value "BE"  (for best estimate).  There are some obs4MIPs datasets that provide multiple estimates derived using various processing choices.  The members of the resulting ensemble of observational estimates will be uniquely identified using the variant_label.

**Comment by scott-stevens** [comment]
Great, thank you for that.  This is a very helpful document.
