### ISSUE TITLE
obs4MIPs_table_id.json has incomplete table names.

### ISSUE THREAD

**Issue by JimBiardCics** [PCMDI/obs4MIPs-cmor-tables#79]
The obs4MIPs_table_id.json file contains the names "Aday", "Amon", "Lmon", "Omon", "SImon", and "fx", but the obs4MIPs_CV.json file contains the names "obs4MIPs_Aday", "obs4MIPs_Amon", "obs4MIPs_Lmon", "obs4MIPs_Omon", "obs4MIPs_SImon", and "obs4MIPs_fx".

Not a major issue if you guys are keeping the obs4MIPs_CV.json file up to date, but it is a discrepancy.

**Comment by durack1** [comment]
@JimBiardCics thanks, good catch.. I'll sort that out today, with a number of other tweaks
