### ISSUE TITLE
Default Title

### ISSUE THREAD

**Issue by Funkensieper** [PCMDI/obs4MIPs-cmor-tables#81]
According to ODS the ``title`` attribute is optional. But if it is omitted, CMOR generates a default title:

https://github.com/PCMDI/cmor/blob/15cc5c4e8c9f2ebdf505f01f9c86e4551eaf819c/include/cmor.h#L186

The "model output" part is not appropriate for obs4MIPs.

**Comment by durack1** [comment]
@Funkensieper thanks for pointing this out. I personally think that a title is an important global attribute, as a number of software packages use this when generating plots.

@taylor13 @gleckler1 do you have any comments to add?

**Comment by gleckler1** [comment]
@Funkensieper We expect to resolve this within the next 48hrs

**Comment by gleckler1** [comment]
@Funkensieper This has been fixed and should be available in CMOR 3.2.8
https://github.com/PCMDI/cmor/blob/98990db87affaa9102de0a11c3c0ed624e478897/include/cmor.h
