### ISSUE TITLE
revision of institution_id registration???

### ISSUE THREAD

**Issue by taylor13** [PCMDI/obs4MIPs-cmor-tables#9]
## Do you want to include the details about which characters are allowed in institution_id?  Here's what I wrote for the CMIP6 registration instructions:

To register (or edit) information about your institution, please title your issue "institution_id registration of [acronym for your institution]" and provide the following information:

'institution_id' -- a short acronym suitable for search interfaces and sub-directory names (should limit the characters used to the following set: a-z, A-Z, 0-9, and "-") 'institution' -- full name and address of institution, likely to include: laboratory/group name, hosting institution name, city, state/province and postal-code, country (no restriction on character set).

Example 1: [title your issue "institution_id registration of PCMDI"]

institution_id = PCMDI
institution = Program for Climate Model Diagnosis and Intercomparison, Lawrence Livermore National Laboratory, Livermore, CA 94550, USA

Example 2: [title your issue "institution_id registration of NASA-GISS"]

institution_id = NASA-GISS
institution = NASA Goddard Institute for Space Studies, New York, NY 10025, USA

**Comment by durack1** [comment]
@taylor13 if you wanted to revise the template [PCMDI/obs4MIPs-cmor-tables/.github/ISSUE_TEMPLATE.md](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/.github/ISSUE_TEMPLATE.md) feel free.. It would certainly be good to get some feedback on this from @JimBiardCics - in addition to capturing information for new variables

**Comment by durack1** [comment]
@gleckler1 pinging you on this

**Comment by gleckler1** [comment]
@taylor13 @durack1  I think this is no longer relevant

**Comment by taylor13** [comment]
What's not relevant?  We *do* want them to register their institution_id and institution.

**Comment by durack1** [comment]
@taylor13, @gleckler1 has already updated the templates which is what the original issue was about - we can keep tweaking these, but for all intents and purposes the issue is resolved (and closed)
