### ISSUE TITLE
Updates in preparation for ODS-2.1

### ISSUE THREAD

**Issue by durack1** [PCMDI/obs4MIPs-cmor-tables#91]
The specifications detailed in https://goo.gl/jVZsQl require changes in this repo. This issue will capture changes in a linked PR

**Comment by gleckler1** [comment]
@durack1 Shall we put a list of changes needed or is it all clear enough to you (the one making changes)?

**Comment by durack1** [comment]
@gleckler1 point your browser to https://github.com/PCMDI/obs4MIPs-cmor-tables/pull/92/files and provide a review - everything that I noted yesterday is implemented
