### ISSUE TITLE
StdDev ancillary variables?

### ISSUE THREAD

**Issue by JimBiardCics** [PCMDI/obs4MIPs-cmor-tables#96]
@gleckler1 @durack1 What about ancillary variables containing standard deviations for a primary variable (to go with Nobs)?

**Comment by taylor13** [comment]
@JimBiardCics Currently I think we suggest reporting the Stderr and Nobs.  Are there good reasons also to report StdDev?  (Hope I haven't just asked a question a high school student should be able to answer.)

**Comment by JimBiardCics** [comment]
When the (for example) monthly values being reported are means of daily values, the two relevant ancillary variables (to me, anyway) are number of observations and standard deviation. Standard Error is a measure of measurement uncertainty - as opposed to statistical variability. You can have a StdErr even when you haven't taken mean, and it can vary from measurement to measurement based on variations in input uncertainties and variations in the algorithms used to produce the measurement from the inputs.

**Comment by taylor13** [comment]
o.k.  I was thinking of the simple case of independent samples used to compute the mean, when stderr can be calculated directly from std dev. and num. of obs.  I tend to agree that there may often be value in reporting the standard deviation of the samples used to compute the mean (instead of or in addition to the standard error).  We'll have to check with the obs4MIPs panel to set a policy about this.  If allowed, the standard deviation would be recorded similar to nobs (with a modifier attached to the standard_name.

**Comment by JimBiardCics** [comment]
Yes. This was the case for the CMIP5 obs4MIPs. It's all wobbly in my book, but the CF definition is

>standard_error: The uncertainty of the data value. The standard error includes both systematic and statistical uncertainty.

StdDev appears to be a measure of statistical uncertainty only in the CF view, and is indicated in the cell_methods attribute. StdErr is indicated by a standard_name modifier.

**Comment by durack1** [comment]
@JimBiardCics this is an effective dupe issue of #50, not sure how we attempt to merge the comments in each to resolve the `Nobs`, `Stderr`, `Stddev` issue

**Comment by gleckler1** [comment]
@JimBiardCics  FYI the obs4MIPs task team will be discussing during its next call whether or not to retain the original (2012) obs4MIPs recommendation to provide two ancillary files for monthly means (only):  Nobs and Stderr.   We'll keep you posted.

**Comment by JimBiardCics** [comment]
@gleckler1 So I'm asking this because there was a long discussion about standard_error about 4 years ago on the CF mailing list. The assertion was made that the standard_error modifier was intended to indicate that the variable it was associated with contained "instrumental errors" as opposed to the results from simple time averaging. I'm not a strong statistics guy, so I am trying to muddle through all this as best I can.

In the CMIP5 version of obs4MIPs there was a place for stdDev. Please correct me if I'm wrong, but it seems to me that there's a few different use cases here.

1. I am not taking a mean and my input data provides uncertainties:
`Use a Stderr variable to report the uncertainties.`
2. I **am** taking a mean, and my input variable does not provide uncertainties:
`Use Nobs and Stddev variables to report the statistical variability of the results of taking the mean.`
3. I **am** taking a mean, and my input variable **does** provide uncertainties:
`Use all three variables to report the mean uncertainties as well as the statistical variability from taking the mean.`

**Comment by Funkensieper** [comment]
I agree, there should be a possibility to report statistical variability via the standard deviation. If only standard error was supported, the user might tend to calculate it via ``stddev/sqrt(nobs)``, which is not correct in most cases (many time-series are auto-correlated and/or exhibit a diurnal/annual cycle).

@gleckler1 I think it is more intuitive to store ancillary variables in the same file (instead of separate files) and use the ``variable_id`` attribute to point towards the primary variable in the file

**Comment by taylor13** [comment]
Including more than 1 field (variable) per file would preclude use of CMOR, and generalizing CMOR to multiple variables will not be possible with current or expected future funding.  So, although I agree it would be more intuitive to include the statistics in the same file as the primary variable, we won't be able to support it.  [Also, I don't think those statistics would be visible with the current ESGF publishing capability.]

**Comment by gleckler1** [comment]
@Funkensieper   @JimBiardCics   Agreed on the different use cases stated above.  In the original obs4MIPs specs, #2 was the target (for stderr).    It is unclear if stderr and nobs (and stddev?) will be expected (~required) fields in obs4MIPs.   This needs to be flushed out by the task team.   It is possible that the focus will remain on the best estimate, and these basic statistics will get migrated to "supplemental info on best estimate":  see https://docs.google.com/document/d/1BmmSWBY8KuS75_9REXqLQPWV-O0BeFCe50uF9mPftls/edit
So, for now I suggest you don't consider these as mandatory.   We will keep you posted on what is decided (probably in October).   Thanks for asking!  

To reiterate KET's point, the emphasis of the current system (data organization, CMOR, COG, ESGF) has been to support the one variable/file data structure that is used for MIPs.  There may come a time to revisit this with observations (indeed we are discussing including in-situ data in obs4MIPs), but generalizing beyond the current structure will require significant investment.
